### PR TITLE
Fixed styling bug

### PR DESCRIPTION
**Pull request by akashnimare**
On this [page](http://www.getmdl.io/styles/index.html)
Here it is

### CODE REVIEW

**Comment by akashnimare** [comment]
I signed it!

**Comment by akashnimare** [comment]
@addyosmani  @sgomes does it look good?

**Comment by sgomes** [comment]
Thanks for the PR, @akashnimare! I'm afraid this change would affect much more than just the bit in the screenshot, though, as it would remove the bullet point from every `li` in all of the text everywhere on the styles and readme pages.

I'll prepare a different PR and link to it here, so you can take a look at a better way of solving this.

**Comment by sgomes** [comment]
Created #1709 with a better solution to this issue.

**Comment by akashnimare** [comment]
@sgomes as for as I know it's not affecting  any other styling. You can cross check it. But you know better so I'll just wait for your PR.

**Comment by akashnimare** [comment]
@sgomes as for as I know it's not affecting  any other styling. You can cross check it. But you know better so I'll just wait for your PR.

**Comment by sgomes** [comment]
@akashnimare No worries, these things are hard to spot sometimes :)

Here's an example of something that would have been affected. Before:

image

After:

image

**Comment by akashnimare** [comment]
@sgomes Ahha! It was so small that I did not spot it.
Your solution is better :+1:

**Pull request closed without merging**
