### PR TITLE
Provide the ability to upgrade a set of elements.

### PR DESCRIPTION
**Pull request by Zodiase**
I hope this looks like what @Garbee had in mind. And unfortunately I couldn't find a place to add `jsClass` so that it somewhat matches the interface of `upgradeElement`.

### CODE REVIEW

**Comment by Garbee** [comment]
The recursive parameter is needless, drop that. We have `upgradeElement` if you need to upgrade a single item. This method is specifically to upgrade many items.

**Comment by Zodiase** [comment]
@Garbee 
I added the the recursive option in case the user has all the elements in an array and doesn't need waste time going deeper into any of them.
The first argument takes an Array of elements, or a NodeList, or a HTMLCollection, or an element (in which case I think the user would set the recursive flag).

**Comment by Garbee** [comment]
If people have it in an array already, then can loop over that in their space and call `upgradeElement` on each directly. Let's keep the core as simple to test and understand as possible and worry about niche cases as they arise. Best have things to add later then be stuck with extra complexity that isn't necessary.

**Comment by Zodiase** [comment]
@Garbee 
Ok, makes sense :)

**Comment by Garbee** [comment]
Sweet, changes lgtm. I'll work on some unit tests to add in before this gets pulled in. Still need review from others as well.

cc @jasonmayes to take a look at the addition. @surma and @sgomes as well if they have the time.

**Comment by Zodiase** [comment]
@Garbee
I happen to have finished this one test case so I'll just push it. I'll leave the rest to ya :)

**Comment by Garbee** [comment]
[All ready](https://github.com/Garbee/material-design-lite/commits/upgradeElement-recursive) for pushing once we have more approval.

**Comment by addyosmani** [comment]
LGTM once we have one more review in. Thanks for the replies to my comments.

**Comment by Garbee** [comment]
Assigning to Jason for a quick review since he is the original creator. If he gives an lgtm we can pull in.

**Comment by jasonmayes** [comment]
LGTM though you know my thoughts on foreach loops and their slowness on arrays. It would be nice to keep everything consistent as mentioned in other requests for readability. Apart from that though, all good.

**Comment by Garbee** [comment]
I'll merge the upstream changes into my branch and push in the morning then. Thanks Jason!

**Comment by Garbee** [comment]
Just pushed the update. Commit 260c88f1bb1b630accd6847f50348a6debe71876 .

**Pull request closed without merging**
