### PR TITLE
fix to handle if Tab has no href attribute

### PR DESCRIPTION
**Pull request by kkpoon**
when tag of Tab has no href attribute, error thrown

`Uncaught TypeError: Cannot read property 'charAt' of null`

### CODE REVIEW

**Comment by kkpoon** [comment]
I signed it!

**Comment by Garbee** [comment]
In what use-case would you not provide a reference?

**Comment by kkpoon** [comment]
In my case, I handle the tab being clicked by onClick, I didn't add a href and having this error `Uncaught TypeError: Cannot read property 'charAt' of null`

**Comment by sgomes** [comment]
Hello there! We're currently doing some housecleaning on the repository to prepare for the big changes to v2, and part of this is to close the mdl-1.1 and mdl-1.2 branches, and move all 1.1 and 1.2 PRs to the mdl-1.x branch. Since it's not possible to target PRs at a new branch, we're closing this PR and asking you to reopen against mdl-1.x if you think it's still valid.

Thank you!

**Pull request closed without merging**
