### PR TITLE
Fixes #376. Uses timeout to prevent events that trigger multiple even…

### LINKED ISSUE #376: MDL Button animations do not trigger upon "tapping" on MacBookPro touchpad
The animations applied to an MDL Button such as "raised button" or the ripple do not trigger when I simply "tap" on my MacBookPro touchpad.

Animations are triggered correctly when I do a "physical" click.

To test this you need to enable the "tap to click" option on the Trackpad's menu in System preferences. Then just "tap" your trackpad instead of doing a click.

### PR DESCRIPTION
**Pull request by akotlar**
### MDL version: 
1.1
### Browser: 
Chrome, Firefox
### Browser version: 
Chrome 51.0.2704.103 , Firefox 47.0 
### Operating system: 
OSX Yosemite
### Operating system version: 
10.10.5
### URL, if applicable 
[Plnk](http://plnkr.co/edit/p1T5fRDDPbqnhKfyk0Ky?p=info)
[Youtube Demo]( https://youtu.be/kyUK9N-1wA8)

#### What steps will reproduce the problem:
1. Tap on any mdl button, using a Macbook Pro touchpad

#### What is the expected result?
Ripple Animation

#### What happens instead of that? 
Nothing, and on occasion, short ripple.

#### Please provide any other information below, and attach a screenshot if possible.
Demo of this is provided

### CODE REVIEW

**Comment by akotlar** [comment]
Thanks to sompylasar and Garbee for guidance. Based on conversation with sompylasar, chose not to use .bind(this) in this solution. Took inspiration from [Angular Material ripple.js](https://github.com/angular/material/blob/master/src/core/services/ripple/ripple.js) to capture ```this```. ```ctrl``` chosen because couldn't find a shorter 4 letter abbreviation that made more sense (and don't like ```that```). 

window.setTimeout and window.requestAnimationFrame used in favor of setTimeout and requestAnimationFrame to fit with 1.1 use of the same.

**Comment by akotlar** [comment]
I still on occasion see flashing animation, I think related to the use of clearTimeout.

**Comment by akotlar** [comment]
I don't think this is ready to merge. This pr still has a race condition between mouseup and mousedown, which can lead to the ripple container being hidden prematurely. Can be triggered by a well timed double or triple click. I'm happy to take suggestions, would love to contribute, thanks for your time.

**Comment by sgomes** [comment]
Hello there! We're currently doing some housecleaning on the repository to prepare for the big changes to v2, and part of this is to close the mdl-1.1 and mdl-1.2 branches, and move all 1.1 and 1.2 PRs to the mdl-1.x branch. Since it's not possible to target PRs at a new branch, we're closing this PR and asking you to reopen against mdl-1.x if you think it's still valid.

Thank you!

**Comment by akotlar** [comment]
Ok, thanks for letting me know!

**Pull request closed without merging**
