### PR TITLE
Adding options for hiding drawer buttons (always and desktop only). Fixes #1462.

### LINKED ISSUE #1462: navbar spacing
the navbar has space for `mdl-layout__drawer-button`, but if you get to delete still have an extra space by default:
```css
padding: 0 40px 0 80px;
```
eg: http://codepen.io/Bound3R/pen/waVeYO?editors=100

### PR DESCRIPTION
**Pull request by sgomes**
This touches tabs as well because they need to be aligned to the title.

@surma @addyosmani PTAL!

### CODE REVIEW

**Comment by sgomes** [comment]
For reference, here are some desktop and mobile views.

Drawer button:

image

image


No drawer button:

image

image

**Comment by Garbee** [comment]
LGTM

**Comment by surma** [comment]
@sgomes Before I whip something up on my own again, do you have a codepen at hand for cross-browser shenanigans?

**Comment by sgomes** [comment]
Can't really codepen this very well, because it's not a one-line fix. I suggest you instead pull the branch locally, `gulp serve` and just add the classes to the layout demos in the docs with DevTools.

**Comment by addyosmani** [comment]
Changes LGTM, @sgomes

**Comment by sgomes** [comment]
Two LGTMs is probably fine :) If @surma finds something, I'll patch it up separately.

Thanks for the review, @Garbee and @addyosmani!

**Comment by addyosmani** [comment]
:fire:

**Comment by surma** [comment]
“4 out of 5 browsers agree…” :wink:

Didn’t to the full cross-browser run, but worked fine so far. Thanks, @sgomes!

**Comment by sgomes** [comment]
To be fair, I'd be very surprised if there were any browser differences, given this is just using very basic layout stuff. But, well, you never know! ;)

**Pull request merged**
