### PR TITLE
Remove comments after concatenation (fixes #574)

### LINKED ISSUE #574: Add spacing above the footer on the Customize Page
Change padding above footer to be 80 px - really tight right now. (should be the same on all sub pages)
screen shot 2015-07-01 at 12 08 23 pm

### PR DESCRIPTION
**Pull request by surma**
r: @addyosmani

### CODE REVIEW

**Comment by gertcuykens** [comment]
My generated material.css is full of multiple comments? Should that not be cleaned too?

**Comment by Garbee** [comment]
I don't think we are worried about multiple comments in the non minified files. It is expected based on how the import structure is setup.

**Comment by surma** [comment]
@gertcuykens As Garbee implied, we were kind of lazy about this as minification removes all comments anyways.

**Comment by gertcuykens** [comment]
True, but sometimes you want to check what css is generated if you are modifying the scss. I think a cleaned up material.css is also valuable debug information without relying on maps.

**Comment by Garbee** [comment]
I feel like cleaning up the provided `material.css` file is a low priority. We can look into restructuring which will prevent the issue outright in V2. Until then it is a very minor thing to deal with.

**Comment by gertcuykens** [comment]
I agree, just mark it in a future milestone maybe so developers are aware of it.

**Comment by Garbee** [comment]
I don't see why we need to create a new issue for this. It is very minor and will be naturally done. Plus, no functionality changes come from it that people need to be aware of.

**Pull request closed without merging**
