### PR TITLE
Fix footer classes

### PR DESCRIPTION
**Pull request by Garbee**
To address #968. No docs update yet. This is purely the sass code for the proper classnames to get added.

### CODE REVIEW

**Comment by addyosmani** [comment]
Changes lgtm. @Garbee I'd like to land the Sass changes and docs for this at the same time so that if it makes it into the 1.0.1 release (aiming for end of week) users are covered. If you're happy to work on docs separately however we can land sooner.

**Comment by Garbee** [comment]
Issue #1006 is open for the doc changes. Let's land this ASAP so anyone using the sources can get the new classes.

**Comment by Garbee** [comment]
Just did a quick find & replace in the doc page since all the classes needed updating. Figured not much needed to be directly looked at, and I was right.

**Comment by addyosmani** [comment]
lgtm to land. cc @sgomes as an FYI this is landing.

**Comment by peluprvi** [comment]
I think there is something wrong on [this commit](https://github.com/google/material-design-lite/commit/ad403aa13c34b69a8f38acfb587745d2d74fcacf), specifically on line 40:

```css
.mdl-mega-footer--left-section,
.mld-mega-footer__lef-section {
   margin-bottom: $footer-min-padding;
 }
```

**Comment by sgomes** [comment]
Looks like it. Thanks @peluprvi! I'll push a fix for that.

**Comment by Garbee** [comment]
Good catch, thanks for reviewing so closely.

CSS selector tests seem like a good idea... :P

**Pull request closed without merging**
