### PR TITLE
Add sliding active indicator to tabs

### PR DESCRIPTION
**Pull request by webcss**
hopefully drone issue is fixed

### CODE REVIEW

**Comment by surma** [comment]
Thanks, @webcss. This PR touches some very fragile parts so we are going to have to make sure that it works across all browsers. Could you give a short summary of what you are trying to improve here? I am struggling to extrapolate that solely from your commit messages (maybe a link to the part of the MD spec, if adequate)?

**Comment by webcss** [comment]
Hi @surma, this PR fixes #954 , as proposed by [material spec](http://www.google.com/design/spec/components/tabs.html#tabs-specs). You need to scroll to the very bottom of the page to see a video showing the correct tab change animation.

**Comment by Garbee** [comment]
Just pulled this in to check out locally. And the tab indicator for the tabs demo is positioned absolutely to the bottom of the page. This means it is not showing with the tabs as it should. As it is, this can't be pulled in until it is positioned properly.

**Comment by Mistereo** [comment]
How this PR handles resizing?
Seems like we need to recalculate slider position on each resize of container.

**Comment by webcss** [comment]
I guess before I continue with an implementation it should be decided on the component in general, since at the moment there are two implementations that have to be maintained, MDLTabs and MDLLayoutTabs. This is an unnecessary duplication of code which makes it hard to maintain.
Another problem ist selection of the active tab upon pageload: when the page first loads the tab with a class of is_active isn't indicated with the sliderbar, but when you reload the page everything works as exspected. 
In the last buildtest drone failed for some other reaon not related to this PR.
@Mistereo resize handling is currently not implemented, see above.

**Comment by Garbee** [comment]
As far as the duplication, we are stuck with it until 2.X when a lot of refactoring is occurring. Layout is a fragile and major component, we shouldn't do any big modifications since 1.1 is the final planned full release (aside from patches to it.)

The on load thing sounds like an unrelated bug. It should have its own issue for tracking and fixing.

**Comment by sgomes** [comment]
Hello there! We're currently doing some housecleaning on the repository to prepare for the big changes to v2, and part of this is to close the mdl-1.1 and mdl-1.2 branches, and move all 1.1 and 1.2 PRs to the mdl-1.x branch. Since it's not possible to target PRs at a new branch, we're closing this PR and asking you to reopen against mdl-1.x if you think it's still valid.

Thank you!

**Pull request closed without merging**
