### PR TITLE
Resolved Windows build problem

### PR DESCRIPTION
**Pull request by kybarg**
Purely a Windows issue.

### CODE REVIEW

**Comment by kybarg** [comment]
I signed it!

**Comment by kybarg** [comment]
Still the same. Only removing <code>validateLinkBreaks</code> option helps.

**Comment by Garbee** [comment]
I'll test the git config changes. We ideally should not remove this validation since it is important that we keep consistent line endings which this enforces.

One method to solve this however, is to remove this here then create another jscs config (`.jscsrc-strict`) for testing merge requests against. That would then do the line ending validation as to avoid it dropping people out on Windows machines. 

For more info issue #743 brings this up.

**Comment by kybarg** [comment]
Clearing git index magically helped

**Comment by Garbee** [comment]
Yea, index has cached stuff so clearing that after the config change switched line endings for the files.

We should document for Windows users checking it out that they need for force LF ending checkout.

**Comment by Garbee** [comment]
Also, looks like we can do a .gitattributes edit to help force this for the repository. I'll look into that.

**Pull request closed without merging**
