### PR TITLE
Part solution to issue #4831

### PR DESCRIPTION
**Pull request by MicaelaBenitez**
#Part solution to issue #4831 
Hello, I hope this help you with the icon toggle examples that where mention in the issue.

### CODE REVIEW

**Comment by traviskaufman** [comment]
Hey @MicaelaBenitez,

Thanks so much for taking the time to look into this and contribute.

Unfortunately, we were actually referring to the [v2 icon toggle example](../blob/master/demos/icon-toggle.html). We wanted to demonstrate how our v2 icon toggles would look in the scenarios described in the issue. 

If you're interested in helping us out with this, I'd be more than happy to help get you set up developing our v2 code. Otherwise, I'll have to close this PR. But thank you again for looking into this.

**Comment by MicaelaBenitez** [comment]
Hey @traviskaufman, 
Thanks so much for taking your time and answer my pull request.
I'm interested in helping you with the project so I'll wait for an answer to get started with the new version.

**Comment by MicaelaBenitez** [comment]
I agree


________________________________
De: googlebot <notifications@github.com>
Enviado: martes, 11 de octubre de 2016 01:06 p.m.
Para: google/material-design-lite
Cc: Micaela Benitez; Author
Asunto: Re: [google/material-design-lite] Part solution to issue #4831 (#4842)


Thanks for your pull request. It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

?? Please visit https://cla.developers.google.com/ to sign.

About - Google CLA<https://cla.developers.google.com/>
cla.developers.google.com
When you sign a Contributor License Agreement (CLA), you give Google the legal permission to use and distribute your contribution. You do not surrender ownership of ...



Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

________________________________

  *   If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Check your existing CLA data<https://cla.developers.google.com/clas> and verify that your email is set on your git commits<https://help.github.com/articles/setting-your-email-in-git/>.
  *   If you signed the CLA as a corporation, please let us know the company's name.

-

**Comment by MicaelaBenitez** [comment]
@googlebot , I've change my email address and signed it.

**Comment by traviskaufman** [comment]
Great! Closing this and let's follow up on the issue.

**Pull request closed without merging**
