### PR TITLE
Check if napa exists before running it

### PR DESCRIPTION
**Pull request by RobLoach**
When installing without having [`napa`](https://github.com/shama/napa) installed, installation will fail since it expects napa to be at `node_modules/.bin/napa`.

Checking if napa is available before running it (via [`type`](https://en.wikipedia.org/wiki/Type_(Unix) )) will solve the problem, allowing it to run when it's there, and skipping napa installation if it's not. Also, since npm adds the bin paths for us, we don't need to prefix `node_modules/.bin`.

### Related

In the following issues, there is a temporary fix that uses a tagged version. While it does work, it is not a permanent fix. The proposed solution here will gracefully degrade when `napa` is not there.

* #859
* #888

### CODE REVIEW

**Comment by Garbee** [comment]
I think the existing code fixes the problem. the people having problems are simply using the tagged version that is sadly bugged.

Someone else from the team should double-check my sanity though.

cc @addyosmani or @surma since this deals with the gulp and they know it well.

**Comment by RobLoach** [comment]
I signed it!

**Comment by surma** [comment]
Hey @RobLoach. Thanks for your PR. However, I don’t quite agree with the two fixes you made.

1.) We can’t assume to have `node_modules/.bin` in `$PATH`. We actually ran into that problem on our CI which made us add the more specific path in the first place ([here](https://github.com/google/material-design-lite/blob/ab5e024bd6c0e487f9aea441bc86276dfce07eda/package.json#L73) is commit from 5 days ago).

2.) How could `napa` not be present after running `npm install`? In any case, if `napa` is missing – for whatever reason – we WANT the whole thing to fail as it is part of our website for now.

**Comment by RobLoach** [comment]
Thanks for taking a look!

> 1.) We can’t assume to have node_modules/.bin in $PATH. We actually ran into that problem on our CI which made us add the more specific path in the first place (here is commit from 5 days ago).

Interesting. What version of npm is on the CI? Running scripts through npm should append .bin to `PATH` before executing it:
https://docs.npmjs.com/misc/scripts#path

> 2.) How could napa not be present after running npm install? In any case, if napa is missing – for whatever reason – we WANT the whole thing to fail as it is part of our website for now.

There are a few cases where this can happen. Here are a couple...

1.  If you install the git version of `google-material-design` in a clean directory, napa will not be present.

  ```
  mkdir mdl-test
  cd mdl-test
  npm i material-design-lite@git://github.com/google/material-design-lite.git
  ```
2. If you use semantic version targeting of `^1.0.0` in your package.json file, it will install `material-design-lite`, but not its `devDependencies`, so napa is not present:

  ```json 
  {
    "name": "mdl-test",
    "private": true,
    "dependencies": {
      "material-design-lite": "^1.0.0"
    }
  }
  ```

I understand the temporary workaround is to use `^1.0.0-3`, but it would be good to have a permanent fix that degrades nicely.

**Comment by surma** [comment]
Ah! I understand now. Well, I can promise you, that @addyosmani (and myself) is not happy about our `devDependencies`, since most of them are specific to getmdl.io and not MDL itself. We are looking to fix that.

Looping in @crhym3 and @addyosmani for workaround ideas.

**Comment by xdissent** [comment]
I think you'd want something like `node_modules/.bin/napa mojombo/clippy || true` since `type napa && node_modules/.bin/napa mojombo/clippy` will still fail if napa doesn't exist.

**Comment by surma** [comment]
Holding off on this in favor of #972, which would replace `clippy` and therefore `napa` altogether.

**Comment by surma** [comment]
We just landed #972, so this is obsolete. Thanks for all your suggestions, people :)

**Comment by RobLoach** [comment]
Thanks a lot, @surma! A much more elegant solution.

**Pull request closed without merging**
