### PR TITLE
fix(checkbox): Fix buildDom to use correct class name for mixedmark.

### PR DESCRIPTION
**Pull request by sgomes**
@traviskaufman PTAL!

### CODE REVIEW

**Comment by traviskaufman** [comment]
Eek! Good catch! You'll need to update the unit test as well. Once you do that and CI passes LGTM

**Comment by sgomes** [comment]
Oops! Tests :) Let's see if that builds now.

**Comment by sgomes** [comment]
Looks like it's good to go. Merging in a bit, if there are no objections.

**Comment by traviskaufman** [comment]
Merge away

**Pull request merged**
