### PR TITLE
Throw error objects, not plain strings.

### PR DESCRIPTION
**Pull request by Garbee**
Update to address a problem brought up in the Snackbar review...

### CODE REVIEW

**Comment by surma** [comment]
LGTM. Since this is a very fundamental class, I want at least on other person checking this. @addyosmani @jasonmayes @sgomes ?

**Comment by Garbee** [comment]
It is also a possible minor BC break, but I think we are early enough... Whoopsie and sorry!

**Comment by Garbee** [comment]
cc @samccone  as well to verify this since they are the ones who realized the mistake in my other code.

**Comment by samccone** [comment]
:+1: :a: :heavy_plus_sign:

**Comment by addyosmani** [comment]
LGTM.

**Pull request closed without merging**
