### PR TITLE
Add icon class to fix #1468

### LINKED ISSUE #1468: Material Icons not showing in MS Edge
Environment: MS Edge on Windows 10 vm from modern.ie http://dev.modern.ie/tools/vms/mac/

Material Icons are not being displayed. I was able to reproduce by visiting the preview of the blog template:
screen shot 2015-08-25 at 9 59 38 am

EDIT: 
Confirmed not displaying when defining the icon as:
```
<i class="material-icons">add</i>
```

Does display when defining the icon as:
```
<i class="material-icons">&#xE145;</i>
```

Not sure anything can be done about this as it may be a MS Edge "feature."

### PR DESCRIPTION
**Pull request by surma**
Look at that! Icons in IEdge without code points :open_mouth: 
screenshot 2015-08-27 15 59 58

Will merge into master once ACK'd

### CODE REVIEW

**Comment by Garbee** [comment]
As just discussed in gitter, can we go ahead and pull in the full `material-icons` class from upstream with this? Or deal with that in another PR?

**Comment by surma** [comment]
@Garbee Fix'd :)

**Comment by Garbee** [comment]
One thing commented inline. Other than that, LGTM.

**Comment by addyosmani** [comment]
LGTM. I think @Garbee's comment about reaching out to the icons team here is sound. @sgomes would you mind pinging Josh about this issue and feel free to loop me in?. He'll know who on the icons team can help :zap:

**Comment by surma** [comment]
Friendly ping about this :)

**Comment by sgomes** [comment]
Oops, this fell off my radar. Getting in touch now.

**Comment by sgomes** [comment]
Alright, long story short, this is a bug in the modern.ie VM: http://stackoverflow.com/questions/32061829/microsoft-edge-user-agent-from-modern-ie/32102663#32102663

The fix shouldn't be needed, since things should work properly with a real Windows 10 install or an updated VM. Shall we close this, @surma?

**Comment by surma** [comment]
ACK'd. Thanks for investigating, @sgomes.

**Pull request closed without merging**
