### PR TITLE
Required input validation fix

### PR DESCRIPTION
**Pull request by PingusPepan**
Trying to get required input fields to act like they are supposed to according to MDL definitions here: https://www.google.com/design/spec/components/text-fields.html#text-fields-required-fields
Issue #1502

### CODE REVIEW

**Comment by PingusPepan** [comment]
I signed it!

**Comment by Garbee** [comment]
Can you please explain what this patch is doing logically and how it addresses the concerns of the issue?

**Comment by PingusPepan** [comment]
@Garbee when the input field is not required or is required and dirty it should behave the same way it was behaving until now.
When the input field is required and empty, it does not perform validation on page load but instead waits until blur or change happens and only then it does the validation.
For me it behaves the same as the video here: https://www.google.com/design/spec/components/text-fields.html#text-fields-required-fields

**Comment by PingusPepan** [comment]
I guess that line 223 is questionable, depending on whether you want to display is-invalid state when enabling empty required element.

**Comment by migueltarga** [comment]
Work like a charm!
Thank you!

**Comment by ramyala** [comment]
Any reason why this isn't merged upstream?

**Comment by sgomes** [comment]
Hello there! We're currently doing some housecleaning on the repository to prepare for the big changes to v2, and part of this is to close the mdl-1.1 and mdl-1.2 branches, and move all 1.1 and 1.2 PRs to the mdl-1.x branch. Since it's not possible to target PRs at a new branch, we're closing this PR and asking you to reopen against mdl-1.x if you think it's still valid.

Thank you!

**Comment by kovaacs** [comment]
It's beyond me why this never made it. Really appreciated @PingusPepan !

**Comment by PingusPepan** [comment]
@620hun Thank you. I guess it's my fault that this never made it because when the PR has been closed, I wasn't working with MDL anymore at that time. So I didn't feel like creating new PR and testing against since April modified code.
When I glanced over the mdl-1.x branch textfield.js it seemed that it didn't change that much, so you can apply the changes there, test it and the post a new PR. If you think it is worth the time with v2 probably released.
I have not been using MDL for a long time so I feel like I have no authority to create the PR myself.

I am glad my code was of any help!

**Comment by kovaacs** [comment]
It is indeed working, exactly as it should be. Thanks again. MDL is pretty
much dead, so there won't be a v2. They're working on MDC now, hopefully
that won't have this problem.

**Comment by Garbee** [comment]
Yea, it wasn't really any code changes. Just the structure which we couldn't re-point things. And we need to have things come through the right flow to make sure all the stuff is in place for legal in case they ask.

V2 is now evolved into Material Components for Web. So check that repository out for the latest code. It's now internal to the Material Design team so there is much better collaboration going on to making the spec work with the web vs against it.

**Pull request closed without merging**
