### PR TITLE
Turn widget explicitly on for things that should be.

### PR DESCRIPTION
**Pull request by Garbee**
To go with pr #1013 . Turning on widgets for all things where it should be needed. It seems something in the check may be working sometimes but not others. This way it is clearly enforced for things that need it.

### CODE REVIEW

**Comment by surma** [comment]
Code LGTM. Wondering if this has a performance impact on page load as the upgrade procedure looks for `mdl-js-*` classes.

**Comment by Garbee** [comment]
I don't think there are any perf differences (other than now taking the time to assign the widget property.) The `mdl-js-*` check shouldn't be impacted by widgetizing the components.

**Comment by addyosmani** [comment]
Do we want to hold on merging this for some perf profiling just to make sure?

**Comment by surma** [comment]
Perf impact seems neglectable. Merging.

**Pull request merged**
