### PR TITLE
Fixes element.MaterialRadio.[un]check() calls on radio lists

### PR DESCRIPTION
**Pull request by marekjalovec**
how to reproduce:
1] have multiple MaterialRadio components with identical name
2] call MaterialRadio.check() on two of them

expected: only the second one is selected
actual: both are selected

### CODE REVIEW

**Comment by marekjalovec** [comment]
I signed it!

**Comment by Garbee** [comment]
The code currently fails since you aren't passing the required argument. The proper fix here should be binding the resolution to the current context.

**Comment by marekjalovec** [comment]
@Garbee the onChange_'s event argument is not even used, so i passed null as an argument

**Comment by Garbee** [comment]
Any remarks on binding the existing call? That seems like the best solution to me.

**Comment by marekjalovec** [comment]
existing call ([un]check) does not have an event object, it may be called programmatically. that was my use case. but maybe i just don't understand your point?

**Comment by Garbee** [comment]
After looking through the checkbox code again I see why this is the right fix. Restarting our CI some since it seems PhantomJS is having problems again.

Fix LGTM but we need the CI to pass before we can merge this.

**Comment by Garbee** [comment]
Thank you for the bugfix!

**Pull request merged**
