### PR TITLE
Change example emails to use a test TLD

### PR DESCRIPTION
**Pull request by nicolasgarnier**
r: @surma

### CODE REVIEW

**Comment by Garbee** [comment]
I think officially it should be `example.com`. There was a standard from the IETF (iirc) about that... Maybe `.example` fully got added to it?

Just slightly nit-picking. It lgtm either way.

**Comment by nicolasgarnier** [comment]
Seems `.example` can be used in this scenario: http://tools.ietf.org/html/rfc2606#page-2

https://twitter.com/sindarina/status/618821793265094656 for context. That's the "bug report" :)

**Comment by nicolasgarnier** [comment]
but `example.com` is also fine that's right :) http://tools.ietf.org/html/rfc2606#page-3

OK let me switch to example.com, it actually looks better.

**Comment by nicolasgarnier** [comment]
Done. PTAL

**Comment by surma** [comment]
Extraordinary work. Lgtm

**Comment by sindarina** [comment]
The standard has been around since 1999 :)  You can use either use `.example` if you require more than three domains in your examples or documentation. For three or less, `example.com`, `example.net` and `example.org` are the easiest to use.

**Comment by sindarina** [comment]
There are equivalent standards for the use of IP addresses in documentation, by the way. In case they are needed someplace :)

https://tools.ietf.org/html/rfc5737
https://tools.ietf.org/html/rfc3849

**Comment by nicolasgarnier** [comment]
Thanks @sindarina :D

**Pull request merged**
