### PR TITLE
Tooltip positions

### PR DESCRIPTION
**Pull request by kybarg**
Tooltip position according to class modifier (default BOTTOM)
BOTTOM: 'mdl-tooltip--bottom',
LEFT: 'mdl-tooltip--left',
RIGHT: 'mdl-tooltip--right',
TOP: 'mdl-tooltip--top'

### CODE REVIEW

**Comment by surma** [comment]
@kybarg We just opened the merge window for MDL 1.1. Would you mind rebasing your PR against the current master so we don’t have any conflicts?

**Comment by kybarg** [comment]
@surma ok, I'll do it tomorrow

**Comment by kybarg** [comment]
@surma can you help me to do that?) First time doing "rebase" and i think i've broken smth.

**Comment by tleunen** [comment]
Make an interactive rebase so you can remove the merge commits ;)
https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase-i/

**Comment by surma** [comment]
Make sure you have your master sync'd with our master!

```
$ git checkout Tooltip-positions
$ git rebase master
... while(conflicts) {
... resolve conflicts
$ git rebase --continue
... }
$ git push origin +Tooltip-positions
```

**Comment by kybarg** [comment]
@surma Thanks a lot, done

**Comment by surma** [comment]
Thank you, @kybarg. We’ll give these a test run soon :)

**Comment by surma** [comment]
`mdl-tooltop--bottom`
screenshot 2015-08-27 14 45 40

`mdl-tooltop--top`
screenshot 2015-08-27 14 45 32

`mdl-tooltop--right`
screenshot 2015-08-27 14 45 14

`mdl-tooltop--left`
screenshot 2015-08-27 14 45 07

@kybarg The calculations for `mdl-tooltip--right` seem to be off.  That could be due to some changes in the meantime, thought. Do you mind taking a look at that?

**Comment by tleunen** [comment]
`left` seems also to be too bar on your image @surma

**Comment by mixedCase** [comment]
Any news with this PR?

**Comment by surma** [comment]
Friendly ping, @kybarg :)

**Comment by sgomes** [comment]
@surma Want to take over this one so we can merge? @kybarg has signed the CLA, so we're good.

**Comment by surma** [comment]
Continued in #1959

**Pull request closed without merging**
