### PR TITLE
Update out of sync classnames.

### PR DESCRIPTION
**Pull request by Garbee**
Via gitter, some of the example classnames are out of sync with the new ones.

### CODE REVIEW

**Comment by Garbee** [comment]
Hold on this. Needs removal of some stuff. Title elements aren't defined at all. Completely unless.

**Comment by Garbee** [comment]
Removed the `title-body` entirely. It is not defined and does nothing.

**Comment by sgomes** [comment]
I'm seeing a number of alignment issues after these changes:

image

image

image

Perhaps we should go back to the original list PR and see if things were removed that shouldn't have been?

**Comment by Garbee** [comment]
ugh, cache problems locally testing that one...

Yea, I'll try to track this down exactly later today.

**Comment by sgomes** [comment]
Looks like we'll need to add `display: inline;` to make sure it displays correctly.

**Comment by Garbee** [comment]
Just need to update this selector `.mdl-list__item .mdl-list__item-primary-content .material-icons` with the display. It is caused when you pull the icon font in after our CSS due to specificity... If our stuff is pulled in after the icon style, then the issue doesn't occur. That would explain why my local test worked.

**Comment by sgomes** [comment]
Sounds good!

**Comment by Garbee** [comment]
Wait, should I close this PR and re-open one against the 1.1 branch? We can then merge 1.1 into master as-needed after any patches we do.

**Comment by sgomes** [comment]
Either's good, since master hasn't seen any 2.0 changes yet.

**Comment by Garbee** [comment]
sgtm. I'll finish this up, once it is merged into master I'll do a rebase and push to 1.1 as the first bit of a patch.

**Comment by Garbee** [comment]
Ready for review again. Keeping a specific second commit so the reason for the inline addition is very clear looking through the history.

**Comment by sgomes** [comment]
LGTM, waiting for CI build to complete before merge. Thanks, @Garbee!

**Comment by Garbee** [comment]
And mdl-1.1 is rebased now.

**Pull request merged**
