### PR TITLE
Add componentHanderConfig to configure upgrade on page load

### LINKED ISSUE #4780: Initial component upgrade cannot be prevented.
Initial component registration happens on page load and cannot be deferred or canceled.  This is a problem for me because I am working with the [shadydom polyfill](https://github.com/webcomponents/shadydom) and the initial upgrade prevents slot content from working properly.  This may just be a bug with shadydom, however a developer could conceivably want to defer registration for other reasons, especially if another framework isn't playing nice.

I propose the following solution.

Before loading the mdl javascript, the developer can set `window.componentHandlerConfig = { preventAutoUpgrade: true };`.  When `componentHandler` is created, the `preventAutoUpgrade` property is copied to a `componentHandler.config` object, but defaults to false.  If `preventAutoUpgrade` is true at page load time, the initial `componentHandler.upgradeAllRegistered()` call will not happen.

I'm going to go ahead and implement this on my fork, but I'll make a PR too.  Any suggestions on how to do this better are welcome.

### PR DESCRIPTION
**Pull request by AlexanderOtavka**
Resolves #4780.

You can now, set `window.componentHanderConfig = { preventAutoUpgrade: true };` before including the mdl script to disable the automatic upgrade of all components on page load.

I'm not sure how to document this change for the larger community, but I feel like it should be up on the MDL website.

Also, any suggestions for a better API for this feature are welcome.

### CODE REVIEW

**Comment by AlexanderOtavka** [comment]
I signed it.

**Comment by Garbee** [comment]
Let's discuss things in #4780 before reviewing this PR. I have some concerns which are best discussed in the main thread.

Thank you.

**Comment by Garbee** [comment]
LGTM awaiting review from @sgomes as well before merge.

**Comment by AlexanderOtavka** [comment]
It looks like phantomjs is having trouble installing, but I don't think I caused that.  My branch is a few commits behind, should I merge from the tip of `mdl-1.x`?

**Comment by Garbee** [comment]
Nah, shouldn't be necessary to rebase. I just restarted the builds. It is bitbucket throttling downloads because PhantomJS get's a lot. They really need to move their archive hosting elsewhere.

**Comment by AlexanderOtavka** [comment]
Ok, good.  And thanks for all the advice.

**Comment by sgomes** [comment]
LGTM, thanks @AlexanderOtavka! I'll keep this open a few more days to see if any 1.2.x changes show up, as once this gets merge the next release will have to be on the 1.3.x range.

**Comment by AlexanderOtavka** [comment]
Fantastic, happy to help.

**Comment by traviskaufman** [comment]
@sgomes can we merge this?

**Comment by sgomes** [comment]
@traviskaufman Yup. Let's officially start the 1.3 merge window with this.

**Pull request merged**
