### PR TITLE
Small fixes to docs.

### PR DESCRIPTION
**Pull request by sgomes**
- Removes "copy to clipboard" functionality. It's only marginally useful, and it relies on Flash, which is
  increasingly deprecated.
- Updates theme path for prism syntax highlighting.

@Garbee or @surma: PTAL!

### CODE REVIEW

**Comment by Garbee** [comment]
LGTM just looking over the code right now. Will manually run and verify later today that everything works as expected.

**Comment by sgomes** [comment]
@Garbee: OK to merge?

**Comment by Garbee** [comment]
Oh whoops, forgot to go back and test manually. Doing that right now...

**Comment by Garbee** [comment]
Runs fine here. Merging.

**Comment by sgomes** [comment]
No worries, was nothing urgent :) Thanks, @Garbee!

**Pull request merged**
