### PR TITLE
comment added for consistency reasons

### PR DESCRIPTION
**Pull request by jojow**

### CODE REVIEW

**Comment by traviskaufman** [comment]
What exactly is the basis for this PR? is it that other examples have comments and this one does not?

If that's the case, would you mind running `git commit --amend` and updating your commit msg to be more descriptive? E.g. `Add comment to be consistent with comments above other demo snippets` or the like? 

And thanks so much for your contribution! :)

**Comment by jojow** [comment]
Exactly, I just found it inconsistent while reading the sample on the mdl website.
Just updated the commit message.

**Comment by traviskaufman** [comment]
LGTM @sgomes

**Comment by sgomes** [comment]
LGTM.

Any chance you can squash the changes before we commit, @jojow? Trying to keep the commit history clean :)

**Comment by Garbee** [comment]
@sgomes We can squash using the GH UX so long as the commit history is non-conflicting. If "Squash and Merge" doesn't show by default then press the arrow beside the merge button and select it. Then just verify the commit message before submitting.

**Comment by sgomes** [comment]
Oh, that's good to know! Thanks, @Garbee!

**Pull request merged**
