### PR TITLE
Fix drawer toggle alignment problem.

### LINKED ISSUE #2017: Hamburger menu not vertically aligning with text on Android
If you can see at the top of the website the text does not align with the icon.

screenshot_2015-12-15-21-24-27

### PR DESCRIPTION
**Pull request by Garbee**
Fixes #2017 

Alignment problem was due to incorrect button line-height. Making sure it is set to the height of the header row itself solves the centering issue.

### CODE REVIEW

**Comment by Garbee** [comment]
Assigning to Surma to verify since they initially built this component iirc. Maybe there is some secret meaning in the original path I don't understand.

**Comment by babywarez** [comment]
any updates on this?

**Comment by Garbee** [comment]
Surma needs to review to verify this wasn't done for a reason. That will happen once he has time to look over things here again.

A patch release probably won't be for another week or two anyways. So no real rush on getting his review.

**Comment by babywarez** [comment]
Thank you for the early response. I'll implement something else in the meantime then because OCD.

**Comment by sgomes** [comment]
Hey @Garbee, mind reopening this against `mdl-1.x`? Thanks!

**Pull request closed without merging**
