### PR TITLE
Enable flicky scrolling on iOS Safari

### PR DESCRIPTION
**Pull request by surma**
This needs extensive testing for the different kinds of headers `layout` has.

This will not make V1.

### CODE REVIEW

**Comment by ston3** [comment]
I noticed this when browsing the docs on my iPad. Unfortunately it makes the whole experience rather painful on iOS.

**Comment by tgabi333** [comment]
+1

**Comment by addyosmani** [comment]
I'll get this manually tested on some iOS devices today. Believe @sgomes might have some time to help us with testing this patch so it lands today.

**Comment by surma** [comment]
The current patch fixes the scrolling behavior for most templates except `article`. Also, the microsite has momentum scrolling on the components page _only_ (and even there the sticky nav goes all kinds of crazy). We need to dig deeper here.

**Comment by sgomes** [comment]
The components page is somewhat custom, so I'm not surprised it doesn't work out of the box. I'll give you a hand in figuring out what's happening with that and the article template.

**Comment by surma** [comment]
I think I make it work.

All templates and the microsite behave correctly in both the iOS emulator and on the physical iPhone.

@addyosmani @sgomes Please look at the branch staged here: http://storage.googleapis.com/mdl-gold-surma/index.html and ACK.

**Comment by sgomes** [comment]
No issues with desktop Safari, LGTM.

**Comment by addyosmani** [comment]
Tested on iOS8/touch. Changes lgtm.

**Comment by Ratts704** [comment]
please help me, how to install kernel missing

**Pull request closed without merging**
