### PR TITLE
docs: Add service worker support for microsite

### PR DESCRIPTION
**Pull request by HenriqueLimas**
This PR is related to the issue #740.

### CODE REVIEW

**Comment by Garbee** [comment]
I'd prefer it if we didn't do the snackbar to notify users about this. It is used in demo code just to show things have been registered or done. In the real-world I feel this should in some way just become expected for certain types of apps. If people care to see if there is a SW or if it is registered, DevTools has them covered.

@sgomes Any thoughts on that UX pattern?

Other than that, which I do consider a blocker until we get some concurrence, it seems all right here.

**Comment by sgomes** [comment]
Thanks for the PR, @HenriqueLimas! I just wanted to say that I haven't forgotten about it, but I sadly haven't had the time to review it thoroughly or loop in some of my colleagues, who are more knowledgeable about Service Worker than I am. Hope to get back to you soon after the holidays!

**Comment by HenriqueLimas** [comment]
Thanks @sgomes. No problem, I'll leave the PR open and If you need that I change something I will change.

**Comment by Garbee** [comment]
MDL is winding down in favor of Material Components for Web. As such, adding support for offline docs to MDL isn't a major priority.

Thank you so much for putting the effort in here but there isn't a big enough benefit that will come from merging this due to the changes internally.

**Pull request closed without merging**
