### PR TITLE
⭐️ Add snackbar memory tests

### LINKED ISSUE #1630: 📈 Add memory test for snackbar
:wave: I got this.

### PR DESCRIPTION
**Pull request by samccone**
Fixes #1630

### CODE REVIEW

**Comment by Garbee** [comment]
Do we have to have all the tests in one file? It would be cleaner if we could have a `menuTest` and `snackbarTest` file in the folder. Then make  the test expandable so any new files added in get ran automatically.

**Comment by samccone** [comment]
> Do we have to have all the tests in one file? 

nope we can split it however we want, we can iterate on this format

**Comment by addyosmani** [comment]
:+1: for iterating. I do like the idea of splitting these out into individual files however.

**Comment by surma** [comment]
Yay for code. :+1: for splitting. Thanks for keeping this up2date, @samccone :)

**Comment by surma** [comment]
... don’t care if the splitting is more appropriate in a separate PR or in this one. Either works for me.

**Comment by samccone** [comment]
sweet all split, I did it in a new commit since it touched the other code quite a bit, I also dropped the iteration count because of this fix I made to drool https://github.com/samccone/drool/commit/4c3ac304448509afc0827e34229999ecba707b04

:sparkles:

**Comment by surma** [comment]
Code LGTM.

If you updated drool, does `package.json` need updating as well?

**Comment by Garbee** [comment]
LGTM.

Side note: I would *like* to see if we could make the main test even more dynamic by requiring a tests subfolder and automatically looping over all found files. That way new tests just need to be created in the folder and be ran automatically. However, not a blocker for merge since it can be looked into later without worry.

**Comment by samccone** [comment]
@surma it was a patch release so the ^ picks it up

@Garbee  The moment we add another I will Abstract it more. No need to over engineer at this moment I think. 

Thanks for the eyes guys!

**Comment by surma** [comment]
@Garbee I agree. Let’s do that when we add the next test(s).

**Pull request merged**
