### PR TITLE
Add Snackbar hide method

### PR DESCRIPTION
**Pull request by joaofnds**
Add Snackbar hide method requested on issue #4310

### CODE REVIEW

**Comment by joaofnds** [comment]
I signed it!

**Comment by sgomes** [comment]
Thanks, @joaofnds!

@Garbee, any thoughts on this?

**Comment by Garbee** [comment]
LGTM code-wise, just ran it and it does work fine.

I'd say let's merge for MDL but get guidance from the MD team for MCW before implementing a hide method to make sure they don't mind developers having this control. As far as I can tell the spec clearly says they should timeout with no mention of any other reasons they should close. IMO, this may only be usable by the spec when the action is clicked on snackbars with actions.

**Comment by Garbee** [comment]
Merged on in. Thank you @joaofnds!

**Comment by garnold** [comment]
@joaofnds @Garbee @sgomes Is this going to make it into a release? It would be very helpful!

**Comment by Aculeo** [comment]
I guess this isn't going to happen anymore since MDL is deprecated and replaced by MDC. For what it's worth, the snackbar in MDC has this capability, but migrating is not straightforward at all. Pretty disappointed.

**Pull request merged**
