### PR TITLE
Align icons in headerbar (fixes #787)

### LINKED ISSUE #787: Dashboard template alignment icons
Page: http://www.getmdl.io/templates/dashboard/index.html
image

The alignment of the icons isn't correct

### PR DESCRIPTION
**Pull request by surma**
screenshot 2015-07-07 16 06 17

r: @sgomes

### CODE REVIEW

**Comment by sgomes** [comment]
This change LGTM, thanks @surma. Is this something that can/should be upstreamed?

**Comment by surma** [comment]
@sgomes I was wondering the same thing. This particular fix definitely shouldn’t go upstream, but maybe there’s a more generic solution to this. Will investigate.

**Comment by surma** [comment]
Upstream fix doesn’t seem feasible, would do more harm than good (because we’d have to counter-act the absolute positioning of the icon in an expandable textfields). I vote for merging this.

**Comment by addyosmani** [comment]
Changes lgtm. Nice work, @surma!

**Comment by Garbee** [comment]
Yea, I've done work with this kind of thing before. It is a pain to handle upstream with the current system. :frowning:

**Pull request closed without merging**
