### PR TITLE
Add `mdl-badge--overlap` class

### PR DESCRIPTION
**Pull request by surma**

### CODE REVIEW

**Comment by Garbee** [comment]
LGTM

**Comment by addyosmani** [comment]
LGTM2. Thanks @surma!

**Comment by Garbee** [comment]
Um, if we are doing a `1.0.3` patch then this needs un-merging to follow SemVer more.  This is adding  functionality, not directly fixing an existing bug.

**Comment by surma** [comment]
Damn. Didn’t think about that. Sorry. Will revert

**Comment by surma** [comment]
Thanks for paying attention, @Garbee :)

**Pull request merged**
