### PR TITLE
Added exporter for used with Meteor JS

### PR DESCRIPTION
**Pull request by Zodiase**
When included in a Meteor project as a client side script or part of a package, variables defined with "var" will not be globally accessible and thus need an exporter.

This exporter checks the existence of Meteor environment and attaches `componentHandler` to the `window` object.

### CODE REVIEW

**Comment by Zodiase** [comment]
I signed it!

**Comment by surma** [comment]
@Zodiase Interesting proposal! How would you expect us to ship this? Would you want to see this bundled up with the main `material.js` or would you expect to include this *in addition* to the `material.js`?

I’d assume that #833 might also be of relevance to you.

**Comment by Zodiase** [comment]
@surma 
The world of Meteor JS is quite complicated...
I was using MDL as an external resource (in which case Meteor will not touch it) and everything was so far so good.
But then I saw some people looking for easy setups like:
`meteor add google:mdl`
This could be convenient to many people so I started looking into how to make it possible.

I first saw @krazyeom's [implementation of the package](https://github.com/krazyeom/Material-Design-Lite-package-for-Meteor), which is just a bundle trying to include the necessary files. But that's not enough. (e.g. Can't access `componentHandler`)

I think `componentHandler` is really important to make MDL useful in most Meteor projects since they tend to have many dynamically rendered components that needs to get "upgraded".

The tricky part of exposing `componentHandler` is that Meteor packages can only export global variables "declared without var" ([citation](http://docs.meteor.com/#/full/pack_export)), which is not likely going to work in other environments. So I have to attach it to the `window` object. And then in the Meteor package I'm writing, another script would pick `componentHandler` up and export it.

Since that is the only workaround I have in mind right now, and I'm not sure if you could attach `componentHandler` to `window` in the first place, so... I made that exporter.

Not sure how this could be better integrated other than attaching `componentHandler` to `window`.

**Comment by Garbee** [comment]
Well, if this were accepted in would it need to be distributed in our core JS?

If so, then I would not like the precedent this sets. Plus the addition of extra code for a niche set of users overall.

If it doesn't need to be distributed with our main files, then I'm not sure why it wouldn't just be put into its own repository that people can use as a bridge between MDL and Meteor.

Exposing componentHandler to window is iffy. The entire system is built to reduce conflict as much as possible; as generic as the objects name is, the likelihood increases for a clash.

**Comment by Zodiase** [comment]
@Garbee
jQuery attaches itself to window if available, I don't see how much trouble that causes. Following the instructions of getting started, componentHandler would be on window anyway.

**Comment by Garbee** [comment]
Can we get a clear answer as to where/how this needs to be distributed please? It has been asked twice now and we still don't have a direct answer.

**Comment by Zodiase** [comment]
I'd love the patch to be part of the core JS, if it seems fit.
Although I could think of a more generic patch to be attaching componentHandler to window whenever possible, I did it this way to avoid conflict of interest and serve Meteor community and I agree it's "extra code for a niche set of users ".

**Comment by Garbee** [comment]
> Although I could think of a more generic patch to be attaching componentHandler to window whenever possible

How would that manifest itself code-wise? If that would fix most of these other tools (seems like it would) then that appears to be the best option.

> I'd love the patch to be part of the core JS, if it seems fit.

In my opinion, it isn't. It is for a niche set of users it adds extra overhead for everyone for something they'd never touch/need. That is where it would be best to have that as its own package that Meteor users can pull in as they need it.

If we were to pull this in and add it, the gateway is then open for any other framework/tool/whatever (I honestly can't remember what Meteor is at this point, sorry) to then submit code back that then would be added in for everyone and maintained by the core team. Sets a bad precedent for the project.

We either need to find a single resolution that is usable by the most amount of tools (sounds like attaching to window in some way is the method to go) or these kinds of things need to be their own packages for the people that need them.

**Comment by Zodiase** [comment]
@Garbee
I agree.

I had to add this code clip to have my custom build of `material.js` because it has to be inside `material.js` for it to work. So it seems like it's better for Meteor users (or just me) to do this custom build every time MDL gets updated?

**Comment by Zodiase** [comment]
@Garbee 
The generic way I was talking about would look like [what jQuery has here](https://github.com/jquery/jquery/blob/master/src/exports/global.js).

**Comment by Garbee** [comment]
Seems like the best thing to do would be drop the var statement and/or directly apply componentHandler to the window object when defining it.

@jasonmayes Any input on that kind of change?

**Comment by addyosmani** [comment]
Holding until we've had a chance to get input from Jason on this one.

**Comment by nicolasgarnier** [comment]
+1 for simply doing `window.componentHandler = componentHandler;` as soon as we create the  componentHandler

**Comment by surma** [comment]
I asked @PaulKinlan to hook me up with someone with more Meteor knowledge than me :)

**Comment by Zodiase** [comment]
Oops, please ignore these new pushes. I'm using my master branch to do builds (probably not a good idea). I'd better close this anyway...

**Pull request closed without merging**
