### PR TITLE
Update npm scripts

### PR DESCRIPTION
**Pull request by mh-cbon**
This fix allows to run npm test on a non en-en system.

On my system localized in french, previous script always failed.

`[[ -z $(git status -uno --porcelain) ]]` checks that local files are committed.

`[[ -z $(git cherry -v) ]]` checks there is no pending commits to push.

### CODE REVIEW

**Comment by mh-cbon** [comment]
won t sign the CLA, but you got the idea, right ?

**Comment by mh-cbon** [comment]
see also https://github.com/google/web-starter-kit/pull/799 its another variation.

**Comment by KamranMackey** [comment]
@mh-cbon you need to sign the CLA otherwise PRs cannot be merged.

**Comment by mh-cbon** [comment]
nop sorry.

**Pull request closed without merging**
