### PR TITLE
updated

### PR DESCRIPTION
**Pull request by vschs007**
adjusted  <title>

### CODE REVIEW

**Comment by ZanderBrown** [comment]
Why? `<title>` should be inside `<head>` as [stated on MDN](https://developer.mozilla.org/en/docs/Web/HTML/Element/head) & [StackOverflow](http://stackoverflow.com/questions/38129982/is-it-considered-bad-to-put-the-title-tag-outside-the-head-tag)

And as show in the source of [this page](view-source:https://github.com/google/material-design-lite/pull/5096)
```html






<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">



  <link crossorigin="anonymous" href="https://assets-cdn.github.com/assets/frameworks-d7b19415c108234b91acac0d0c02091c860993c13687a757ee345cc1ecd3a9d1.css" integrity="sha256-17GUFcEII0uRrKwNDAIJHIYJk8E2h6dX7jRcwezTqdE=" media="all" rel="stylesheet" />
  <link crossorigin="anonymous" href="https://assets-cdn.github.com/assets/github-0c93ab9c2e50f29ebbfe9f83d851cc833faef49aaa870ff542e38091d78df240.css" integrity="sha256-DJOrnC5Q8p67/p+D2FHMgz+u9Jqqhw/1QuOAkdeN8kA=" media="all" rel="stylesheet" />
  
  
  
  

  <meta name="viewport" content="width=device-width">
  
  <title>updated by vschs007 · Pull Request #5096 · google/material-design-lite</title>
  <link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="GitHub">
  <link rel="fluid-icon" href="https://github.com/fluidicon.png" title="GitHub">
  <meta property="fb:app_id" content="1401488693436528">
```

**Comment by vschs007** [comment]
Does it affects the code in adverse way ?

**Comment by ZanderBrown** [comment]
Yes because it doesn't follow the HTML standards and there was nothing wrong with the current implementation

In a side note the indentation would be incorrect

**Comment by vschs007** [comment]
Ok i will revert it :)

**Comment by Garbee** [comment]
It doesn't affect the code in an adverse way at all in this situation. Browser engines can handle poorly structured code like this. However, it is technically invalid and doesn't provide any benefit to users so we won't be merging this request. 

Thank you.

**Pull request closed without merging**
