### PR TITLE
Corrected grammatical error and spacing issue

### PR DESCRIPTION
**Pull request by NicolasJEngler**
Correction for a small grammatical error and spacing issue.

### CODE REVIEW

**Comment by NicolasJEngler** [comment]
Signed, sealed, delivered. I’m yours!

Nicolás J. Engler
Front-end developer and graphic designer
(+54) 3496 532965
http://nicolasjengler.com.ar <http://nicolasjengler.com.ar/>

**Comment by Garbee** [comment]
lgtm. Can you squash the commits please?

**Comment by NicolasJEngler** [comment]
Done :+1:

**Comment by Garbee** [comment]
That just made it worse... It is now 4 commits instead of 1 (or even the original two.) Let me see if I can fix this locally...

**Comment by Garbee** [comment]
Fixed with commit 3650b6313ccff37e128bc6929633ffda560158bd.

Thanks!

**Comment by NicolasJEngler** [comment]
I'm really sorry, I just saw this! Thanks for fixing it for me.

**Comment by Garbee** [comment]
np, took me a minute to figure out how to remove merges. Other than that it is pretty painless once you've done a rebase a few times.

**Pull request closed without merging**
