### PR TITLE
Update tab button appearance on window resize. Fixes #4061.

### LINKED ISSUE #4061: Layout tabs slide indicators do not display
The tabs slide indicators appear (transparent) on screen sizes over 1024px (when not needed) and are set to `display:none` on screen sizes under 1024 (when they are most likely to be needed).

Material Design Spec: https://www.google.com/design/spec/components/tabs.html#tabs-usage

Codepen: http://codepen.io/stianflage/pen/qbyawy
(I set the just override the button color to white so it's visible)

### PR DESCRIPTION
**Pull request by sgomes**
@Garbee or @surma: PTAL!

### CODE REVIEW

**Comment by sgomes** [comment]
Build failing, give me a sec to closurify.

**Comment by sgomes** [comment]
Should be good to go now.

**Comment by surma** [comment]
LGTM

**Comment by sgomes** [comment]
Thanks for the LGTM! Just noticed this is set to go against master. Opening a new PR against mdl-1.1.

**Pull request closed without merging**
