### PR TITLE
Add variables for font sizes in components.

### LINKED ISSUE #1347: Checkbox Font Size
Checkbox font size should be inherited with a variable defined globally. I'm not sure if this occurs in other element definitions, but _checkbox.scss has the following:
```css
.mdl-checkbox__label {
...
  font-size: 16px;
```

### PR DESCRIPTION
**Pull request by sgomes**
Fixes #1347 and all the others I could find.
Also removes some dead code.

@surma PTAL!

### CODE REVIEW

**Comment by jhawlwut** [comment]
That's exactly where I had envisioned being able to edit them - thanks @sgomes!

**Comment by surma** [comment]
Code LGTM.

If the Firefox bug we talked about OOB is resolved/unrelated, merge at will :)

**Comment by Garbee** [comment]
The variables should have `!default` if we expect people to modify them easily.

**Comment by sgomes** [comment]
I intentionally left `!default` out of most of those, since they would negatively affect the components. We can add those in if we ever make all of the other component variables `!default` as well and, ideally, calculate them all based on a single `size` variable, to ensure proportions are respected.

**Comment by sgomes** [comment]
Thanks, @surma, merging!

**Pull request merged**
