### PR TITLE
Add the `data-mdl-for` attribute to tooltips.

### PR DESCRIPTION
**Pull request by westy92**
I'm adding the `data-mdl-for` attribute to tooltips just like it exists for menus.

### CODE REVIEW

**Comment by Garbee** [comment]
LGTM. re-running CI in case that was a transient error.

**Comment by westy92** [comment]
Hmm... "Failed at the phantomjs@1.9.7-15 install script 'node install.js'."

**Comment by Garbee** [comment]
I'm holding off on pinging Alex to look into it. I/O just ended so I'd like the team to relax a bit. This also isn't critical so no rush on getting it done.

**Comment by westy92** [comment]
No rush.  Thank you!

**Comment by westy92** [comment]
This closes #4009.

**Comment by Garbee** [comment]
@crhym3 Can you spot off quickly what the source of the failure is here? Smells to me like some drone config may have gotten out of alignment with the `mdl-1.2` branch but I don't know what I'm looking for.

**Comment by crhym3** [comment]
I believe it's this:

```
Error requesting archive.
Status: 403
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-x86_64.tar.bz2",
  "encoding": null,
  "followRedirect": true,
  "headers": {},
  "strictSSL": true
}
```

Hopefully it's just a temporary bitbucket or network failure - I restarted the build.

**Comment by crhym3** [comment]
some closure errors:

```
[19:29:53] Starting 'closure'...

stream.js:74
     throw er; // Unhandled stream error in pipe.
     ^
Error: src/mdlComponentHandler.js:245: WARNING - invalid cast - must be a subtype or supertype
from: (Element|HTMLCollection|NodeList)
to  : (Array|null)
       elements = Array.prototype.slice.call(/** @type {Array} */ (elements));
                                                                  ^

src/tooltip/tooltip.js:79: WARNING - assignment to property top of CSSStyleDeclaration
found   : number
required: string
       this.element_.style.top = 0;
       ^

src/tooltip/tooltip.js:87: WARNING - assignment to property left of CSSStyleDeclaration
found   : number
required: string
       this.element_.style.left = 0;
       ^

0 error(s), 3 warning(s), 93.0% typed
```

**Comment by Garbee** [comment]
Ah, thanks @crhym3. I restarted the build like 3 times trying to see if it was intermittent. So either it was elongated or I didn't actually restart the build.

Those errors are already fixed, just needs `mdl-1.1` merged up.

Going ahead and merging since everything looks good here in light of the CI failure itself.

Thanks for the addition @westy92.

**Comment by westy92** [comment]
You're welcome.  I'm glad I was able to contribute.

**Pull request merged**
