### PR TITLE
update es5-shim

### PR DESCRIPTION
**Pull request by hebbet**
update es5-shim sample in faq

### CODE REVIEW

**Comment by surma** [comment]
I think this is fine to merge. Want at least one other ACK to ensure this does not have any side effects.

@addyosmani @sgomes PTAL

**Comment by sgomes** [comment]
Do we know what this shim is being used for, so we can run some tests?

**Comment by surma** [comment]
I assume it’s for stuff like `Array.prototype.filter` and `Array.prototype.forEach`. Not 100% on that, though.

cc @jasonmayes

**Comment by addyosmani** [comment]
This was indeed for ES5 array methods that were missing. LGTM to merge.

**Comment by jasonmayes** [comment]
I dont think I used any of those in my original code - but what Addy said seems legit.

**Pull request merged**
