### PR TITLE
Standardising function import to use _ and adding license header

### LINKED ISSUE #1345: Different @import in _variables.scss
Is here any reason to make different style imports in https://github.com/google/material-design-lite/blob/master/src/_variables.scss#L70:
```sass
@import "_color-definitions";
@import "functions";
```

Seems like better to have consistently underscored or not. BTW in `src/*/_*.scss` only variant without underscore is used (`@import "../variables";` and `@import "../mixins";`).

Maybe it's very minor issue since doesn't affect final result, but it's sloppy inconsistent.

### PR DESCRIPTION
**Pull request by sgomes**
Fixes #1345.

@surma PTAL!

### CODE REVIEW

**Comment by surma** [comment]
LGTM

**Comment by tleunen** [comment]
This is weird, it doesn't seem to be something widely used. No need to put the underscore in the import statement.

**Comment by tleunen** [comment]
Seems like `variables.scss` is the only place where you put `_`. The right fix would be to remove it, not to add it :)

**Comment by sgomes** [comment]
This change was mostly for consistency, @tleunen; it's easiest to change a single import.

That said, I'll do some digging around to see if this is an anti-pattern or just a harmless odd choice. If the former, a PR might be in order.

**Comment by sgomes** [comment]
@tleunen You're absolutely right! I should fix that, then :)

**Comment by sgomes** [comment]
Done, thanks again @tleunen!

**Comment by tleunen** [comment]
:+1:

**Pull request merged**
