### PR TITLE
Remove unnecessary class

### PR DESCRIPTION
**Pull request by Bound3R**
This double class is unnecessary since already being set.

### CODE REVIEW

**Comment by Garbee** [comment]
Double-classes are done to increase specificity to be more certain the rules get applied.

Even if in this case we *could* remove it, it is a breaking change and can't be done in the 1.x lifecycle.

cc @surma and @sgomes To have a look in case we should put this on the block for 2.0.

**Comment by sgomes** [comment]
We can't really remove it in this case, as we need it to have a higher specificity than the default, and thus override it.

**Comment by Garbee** [comment]
I mean, we have better specificity in terms of pure cascading by having it lower in the sheet than the default. Not sure of a scenario where this double-class is really handy myself.

**Comment by sgomes** [comment]
It could be a legacy issue in this case, or it could be that one of the properties being set in that sub-block gets overridden elsewhere. We could investigate for a v2, but it would indeed be a BC break for now (and while unnecessary, it's probably not causing any immediate issues).

**Comment by Garbee** [comment]
Tagged as needed for us to look into later. Since we can't do anything until a major we shouldn't really put much more thought into this at the moment.

**Comment by Garbee** [comment]
Following #1632 here, closing this out since we will look over selectors in V2 fully to make sure they are as lean as we can get. For now, stuck with it due to BC concerns.

**Pull request closed without merging**
