### PR TITLE
Add search component

### PR DESCRIPTION
**Pull request by eKoopmans**
### Description

This is an MDL search component based off of [this Material.io spec](https://material.io/guidelines/patterns/search.html). It features an input field, dropdown search suggestions, and responsive back/cancel buttons. Search functionality is exposed by two callback functions, `search` and `submit`, which are specified as text attributes on the component.

The component is loosely based off of the `menu` and `textfield` components, which allowed me to maintain some style consistency with those. It can be styled as an inset box (i.e. "Persistent search" in the Material.io spec), a full-header search field, an expandable search field (i.e. "Expandable search"), or an unstyled inline block. It also works in combination with mdl-textfield styling, which is demoed in the snippets.

All documentation and testing is done, though I could use help with further cross-browser testing!

### Todo

- [x] Unit test
- [x] Readme
- [x] Snippets/demo
- [x] docs/_assets/comp_search.png
- [ ] Cross-browser testing
    - [x] Windows
        - [x] Chrome
        - [x] Firefox
        - [x] Edge
        - [x] IE11
    - [ ] Android
        - [x] Chrome
    - [ ] Linux
    - [ ] Mac/iPhone/iPad

### CODE REVIEW

**Comment by eKoopmans** [comment]
So, any feedback? I know your devel efforts are focused on MDC-Web, but it seemed like too much of a moving target to try to develop a new component there directly.

I also know that search is defined as a "pattern" and not a "component", so maybe that's a problem. Is there a reason you don't already have a pre-built MDL search component? It seems like a pretty important feature, and I know others have asked about it (i.e. [here](https://github.com/google/material-design-lite/issues/4554) and [here](https://github.com/google/material-design-lite/issues/4846)).

**Comment by Garbee** [comment]
I mainly need to find the time to sit down and give this a run-through. And test how things work in IE9 and 10 as well. (Even though 9 isn't JS supported I'm still curious on how things end up working.)

It is on my list of things to review, just not sure it will be this week. Most likely if I can't get it done today then Tuesday will be when I can do the tests.

I brought this pattern up before we even launched as well. We decided not to stuff the Layout too much since it was already complex enough. This isn't an easy thing to add and it also looks doing a quick glance over the source like you also included typeahead support which means the review process is even longer because that brings heavy accessibility concerns.

**Comment by eKoopmans** [comment]
Thanks for the response @Garbee! No problem, I'll sit tight. I've put [the docs](http://www.erik-koopmans.com/mdl-search/dist/components/index.html#search-section) and another [quick demo](http://www.erik-koopmans.com/mdl-search/) up on my personal site for testing.

Regarding typeahead, it's designed to have a dropdown of search suggestions that update as you type (as per the spec), but it doesn't modify the search field, and it's agnostic as to how the suggestions are generated. You're just given a callback when search occurs, and you provide your own array of `<li>` elements that you want displayed.

**Comment by ZanderBrown** [comment]
@eKoopmans going to be picky:

It would be nice if the hamburger could rotate into the arrow.
image
and the shadow here somehow doesn't look right

**Comment by eKoopmans** [comment]
> It would be nice if the hamburger could rotate into the arrow.

Sure, why not! I've added that feature, which can be enabled individually on icons by adding the `mdl-search--animate` class - see the [demo](http://www.erik-koopmans.com/mdl-search/) I posted earlier.

> and the shadow here somehow doesn't look right

What part doesn't look right? The shadows there are entirely a product of `mdl-layout`, I didn't change those at all - that's just what a fixed header and drawer look like.

**Comment by ZanderBrown** [comment]
>>and the shadow here somehow doesn't look right
>
>What part doesn't look right? The shadows there are entirely a product of mdl-layout, I didn't change those at all - that's just what a fixed header and drawer look like.

Just checked your right. Probably hadn't noticed it before because the toolbar in the docs's is a dark colour not white.

Quick work on the animation, really makes it appear more 'native'

**Comment by eKoopmans** [comment]
Thanks! I've noticed one problem since adding the animations though: on desktop, the search loads on the left edge of the screen before the drawer, and then gets noticeably bumped over once the drawer's loaded. Could just be an interaction with my 'autofocus' of the input field though, I'll check into it later.

**Edit:** Fixed - it was a problem in the `mdl-layout` CSS. Right now the `mdl-layout__header` isn't positioned horizontally until after the component is registered in JS (it relies on `is-upgraded` and `is-small-screen`). This isn't necessary, the same `@media` query can be done directly in the CSS, giving the proper appearance even without JS (and no visually delayed adjustment).

For now I've just added that custom CSS to my demo file, but I could make a separate PR to make that change in `mdl-layout` if wanted. I know layout has been changed a lot in MDC-Web, so I'm guessing this isn't even an issue there.

**Comment by eKoopmans** [comment]
Hey @Garbee, has anything changed in the tests? I notice I'm failing now at the same point as #5079, the changes I just made were pretty minor and shouldn't have broken anything.

**Comment by ovo4096** [comment]
demo

@eKoopmans Very nice work, I hope to be able to add a search for this style.

**Comment by eKoopmans** [comment]
Thanks @ovo4096! Interesting, so with a margin around the expanded search box, and a screen overlay. Those are stylistic decisions that I think depend on how the MD team want things to look - the styling I've done is not necessarily right either. I'll wait until I have some feedback from them about those sort of decisions.

P.S. I'd say that the styling you've suggested isn't consistent with [the spec](https://material.io/guidelines/patterns/search.html), which I've tried to follow closely, but again it's not my decision to make.

**Comment by ovo4096** [comment]
@eKoopmans 

dd

Update style

**Comment by eklem** [comment]
Anything happening here? Nice work, @eKoopmans

**Comment by eKoopmans** [comment]
Thanks @eklem! Nothing new on my end, though I might tweak the search callback at some point to integrate more cleanly with React/etc.

**Comment by eklem** [comment]
I'll test your fork @eKoopmans , if nothing else happens here before I start.

**Comment by Garbee** [comment]
We are rounding up one last release of minor things for MDL. Sadly I don't have any real time to put towards maintaining the project further and MCW is now the main focus internally.

Since I can't review this merge of a larger component and no one will be doing any further releases for the project internally, this code can't be merged in.

Thank you for your time here, it is very much appreciated. We do encourage you to release this as a custom package on NPM to get this distributed to developers.

**Comment by ZanderBrown** [comment]
That's a shame but I understand the decision.
Any chance of porting this to MCW?

**Comment by eklem** [comment]
This component in [MCV](https://github.com/material-components/material-components-web) would be really nice. Any chance you'll give it a try, @eKoopmans? I'm not a good programmer, but I'll test and give feedback if you do.

**Comment by Garbee** [comment]
File an issue with MCW on that @ZanderBrown. This is definitely up the wheelhouse there since it is specified, but it wouldn't be a release-level component. I'd wager they try to hold off to do this one post-release since it can be quite complex and other components are a higher-priority to get web apps working.

**Comment by eKoopmans** [comment]
Hey everyone, yeah I've been meaning to port this over to MCW, no worries. I'll give it a shot as soon as I have a chance!

**Comment by Garbee** [comment]
Be sure to follow the MCW contributing guide please! They would like a detailed document on the feature and implementation details before any coding is started. That way it can be thought over before the heavy time investment into coding is put in. It will also make for a smoother merge process later on.

Thank you.

**Comment by eKoopmans** [comment]
Thanks @Garbee, I will. Sorry I didn't give anyone a heads-up before I submitted here, I had already mostly created the component for myself before submitting it to MDL.

**Comment by Garbee** [comment]
I didn't mind it getting submitted at all. I just never found the time to really review it in detail in order to feel safe merging it for release. And since we just decided to do one last release I don't want to add anything too major, especially scripting related.

**Pull request closed without merging**
