### PR TITLE
Fix #702, Multiplication different types crash gulp-sass

### LINKED ISSUE #702: Sass upgrade blocked by mixed units
I tried to upgrade to libsass 3.2.5, but it's unhappy with the way we use units in one place:

```
Error: src/_variables.scss
  308:20  Incompatible units: 'ms' and 'deg'
```

Mentioned piece of code:

```sass
// Amount of circle the arc takes up.
$spinner-arc-size: 270deg;
// Time it takes to expand and contract arc.
$spinner-arc-time: 1333ms;
// How much the start location of the arc should rotate each time.
$spinner-arc-start-rot: 216deg;

$spinner-duration: 360deg * $spinner-arc-time / (
    $spinner-arc-start-rot + (360deg - $spinner-arc-size));
```

I think this is due to the changes introduced in https://github.com/sass/libsass/issues/1167.

Nothing critical at all, just to bear in mind for future update.s

### PR DESCRIPTION
**Pull request by domio**

### CODE REVIEW

**Comment by Garbee** [comment]
Is there any bug or problem this is fixing in the existing code?

I don't see any real reason for us to upgrade the `gulp-sass` at the moment when everything is working fine and we aren't using the new features yet.

**Comment by domio** [comment]
#702

**Comment by domio** [comment]
I revert gulp-sass version

**Comment by Garbee** [comment]
@passy Do you have a moment to check this and see if it fixes the issue raised in #702?

**Comment by passy** [comment]
@Garbee Looking into it now. :)

**Comment by passy** [comment]
Yup, brilliant, this fixes the issue. And we can upgrade to the newer `libsass` which is a lot faster (at least on my machine).

:+1:

**Comment by Garbee** [comment]
Fantastic, thanks Passy!

**Comment by addyosmani** [comment]
Awesome!

**Pull request closed without merging**
