### PR TITLE
Test Component handler

### PR DESCRIPTION
**Pull request by Garbee**
Starting work on testing the component handler for issue #899. This should ease our minds going forward with any modifications to it.

As I'm writing anyone can keep an eye on the work here. If you want to submit a test, submit against the test-handler branch. If you have a request of what should be tested that isn't currently shown, just comment here.

* [x] Check errors when improperly registering a new component
*  ~~Check how methods fail when not provided the proper parameters.~~
* [x] Check upgrading entire DOM.

### CODE REVIEW

**Comment by addyosmani** [comment]
@Garbee Thanks for working on this. Are tests for componentHandler something we want to try landing for the 1.0.1 milestone? They're not really tied to it, but we can make sure to track it as part of the release if needed.

**Comment by Garbee** [comment]
Let's land as many as I can get done before tagging and move forward from
there.

**Comment by nicolasgarnier** [comment]
Cool thanks for starting this. Just added one :)

**Comment by Garbee** [comment]
Dropped checking parameter differences for initial pull. Due to multiple flows of logic, doing deep testing on them is going to take some time. Let's focus on covering the basic ground and external view on upgrades occurring. We can slowly add in deeper coverage of the public methods later.

**Comment by Garbee** [comment]
Review time!

I think this is good enough to land for initial testing. Still taking orders for recommendations (that don't involve testing one method 3 or 4 different ways.)

**Comment by Garbee** [comment]
That test would belong under Ripples since that is more of a test of that component itself over the componentHandler doing its job.

**Comment by Garbee** [comment]
Let me *attempt* a squash locally, going to be new trying to keep one commit as-is and squash into two commits around it.

**Comment by addyosmani** [comment]
Were/are you intending to squash to one commit? (or is the current 2 x Garbee, 1 x Nicolas commit queue intentional)? :)

**Comment by Garbee** [comment]
Yea, I will attempt to get it into one by me. The issue previously was his was in the middle, I was afraid of what may happen if I squashed right through (maybe it would have lost his name on the commit) decided to not test the waters that far. But, let me see what happens locally squashing even further (since it seems to have re-ordered on its own)....

**Comment by Garbee** [comment]
Yea, can't squash any further. It will lose Nick's name to his addition.

**Comment by addyosmani** [comment]
No worries! I think it's fine as is as you've already tries squashing whilst maintaining commit authorship. I'm happy with the current state of these tests. LGTM.

:horse_racing: :cake:

**Pull request closed without merging**
