### PR TITLE
Use actual colors

### PR DESCRIPTION
**Pull request by glebm**
Following up on the internal discussions. Words are cheap, code is gold.

* Use actual colors everywhere, remove `unquote` stuff.
* Define `rgba-tpl` function for generating (invalid) CSS templates (literal `rgba($var, 0.5)`).

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks for the PR, @glebm. We're going to take some time to review the implementation here and discuss it with the core team. We appreciate you working on this.

**Comment by glebm** [comment]
Cheers! Reverted the `strip-units` change as `unitless` does not do what I thought it did.

**Comment by gauntface** [comment]
This gets a big thumbs up from me.

**Comment by surma** [comment]
:+1:

**Comment by Garbee** [comment]
This is a BC break for anyone using the Sass in their own build pipeline. Can't merge before 2.x.

**Comment by sgomes** [comment]
I'm not sure how much of a BC break this is for folks using SASS, actually, @Garbee. If they're relying on the palette variables directly, perhaps (and I'd argue those should be considered private), but it otherwise seems compatible with our previous variable format.

It seems to me that if you're just defining `$color-primary` and friends, things should still work. I'll run some tests when I get a chance and comment again.

**Comment by glebm** [comment]
I have looked into making it backward-compatible:

1. The `rgba-tpl` is already backwards-compatible, but could use a warning like this:

    ```sass
    @if str-index($color, ",") {
          // TODO: remove for 2.0 release.
          @warn "Please change your variables to use colors. Using strings is deprecated and will be removed in 2.0."
    }
    ```

2. There are a number of places that previously used `unquote("rgb(..."`, such as:

    ```diff
       .mdl-color-text--deep-purple-A400 {
    -    color: unquote("rgb(#{$palette-deep-purple-A400})") !important;
    +    color: $palette-deep-purple-A400 !important;
       }
    ```
  These would require introducting another function such as `color-or-string` to be backwards-compatible. Let me know if you want this done, or rather postpone for v2.

**Comment by Garbee** [comment]
This *has* to be postponed to 2.0. Internally we can update all we want. Other developers however may have included MDL and used the Sass in their pipeline, then used the unquote hack in their code to get the colors. That means it is a breaking change.

**Comment by glebm** [comment]
The point is that this can be made backwards-compatible with the unquote hack.

**Comment by Garbee** [comment]
Ok, I'm confused on that one. If someone already has `unquote("rgb(#{$palette-red-50})")` defined in their Sass, wouldn't that break once RGB values are introduced? I don't see how it wouldn't unless we override unquote somehow.

**Comment by sgomes** [comment]
Merged with #4167, thanks @glebm and everyone who reviewed this.

**Pull request closed without merging**
