### PR TITLE
Added functionality to allow forcing a mobile site layout

### PR DESCRIPTION
**Pull request by merken**
Header will be permanently compact, header is toggleable, opening the menu does not cause the header to be de-compacted

### CODE REVIEW

**Comment by merken** [comment]
old : https://pbs.twimg.com/tweet_video/Ckk_3CiUgAAIATt.mp4

new : https://pbs.twimg.com/tweet_video/CklAAp6UoAEb6zx.mp4

**Comment by merken** [comment]
Just noticed the changes are all over the place due to VS Code formatting my source code.
Please check out the //MME comments for actual changes.

Sorry for the hassle

**Comment by surma** [comment]
Thanks for your effort, @merken! I am happy to review this, but please revert the formatting changes first. Not all of them comply with our style guide and formatting fixes should be done in a separate PR. Also please don’t mark your comments with initials. Someone who wants to read this code in the future will not know what “MME” stands for and it will just cause confusion.

**Comment by merken** [comment]
Reverted formatting, removed comment prefixes, as requested.
Re-applied the changes.

**Comment by Garbee** [comment]
Can you please point out where this comes from in the specification? I don't know off-the-top if this kind of UX is something they allow as an option directly or if it is something developers simply want as an alternative.

Further, `master` is going to undergo major changes for V2 and the layout structure will change completely. This should go into the `mdl-1.2` branch as it is a new feature for that release to make it to end-users.

**Comment by sgomes** [comment]
Hello there! We're currently doing some housecleaning on the repository to prepare for the big changes to v2, and part of this is to close the mdl-1.1 and mdl-1.2 branches, and move all 1.1 and 1.2 PRs to the mdl-1.x branch. Since it's not possible to target PRs at a new branch, we're closing this PR and asking you to reopen against mdl-1.x if you think it's still valid.

Thank you!

**Pull request closed without merging**
