### PR TITLE
Display color name on the wheel with tooltip #516

### PR DESCRIPTION
**Pull request by surma**
Rebased version of #1484.

Firefox and Safari both work, probably due to the tooltip fixes/enhancements that landed in the meantime.

### CODE REVIEW

**Comment by surma** [comment]
Author @kingstenbanh has signed the CLA, as can be seen in the original PR.

**Comment by addyosmani** [comment]
Changes LGTM.

**Comment by addyosmani** [comment]
@surma merged this one to master - do you want me to land this in the 1.0 branch too?

**Comment by surma** [comment]
Yes. I assume the website will be deployed from the `mdl-1.0` branch until we push 1.1

**Pull request closed without merging**
