### PR TITLE
Looked at the CSS and updated accordingly

### PR DESCRIPTION
**Pull request by cliffordp**
https://storage.googleapis.com/code.getmdl.io/1.0.0/material.indigo-pink.min.css

Search for 'mdl-shadow--' and there only shadow classes that exist are for 2, 3, 4, 6, 8, and 16

### CODE REVIEW

**Comment by surma** [comment]
Well spotted! The classes used to be called `mdl-shadow--z[1-5]` (or something) and we renamed them to be closer to the spec. Apparently, we forgot the documentation along the way. Thanks alot, @cliffordp. Change LGTM.

**Comment by Garbee** [comment]
LGTM as well, nice catch.

Once the CLA is signed we can merge away.

**Comment by cliffordp** [comment]
CLA signed. Glad to help.

FYI: Working on an MDL Shortcodes plugin for WordPress. So far I've completed Badges, Buttons, Cards, and Grids. Tabs and so on are next.

Please let me know if there's some place to ask questions on my coding journey this week.

For example, I noticed some demo cards had `.mdl-card--expand` but I didn't notice any difference when that was added, and I didn't see it mentioned on that page's documentation.

tyvm for MDL!

**Comment by Garbee** [comment]
I've put `mdl-card--expand` on the chopping block in the next major release. So don't worry about that one. ;) You can find details in issue #1036 on that one.

Support or general questions should be asked on StackOverflow and use the `material-design-lite` tag among any other appropriate tags. The issue tracker is for core problems with what MDL provides.

Thanks for the doc patch as well!

**Pull request merged**
