### PR TITLE
Pr 1367

### PR DESCRIPTION
**Pull request by surma**
Re-PR-ing #1367, as I merged too early once again and had to revert. Already ACK'd.

### CODE REVIEW

**Comment by surma** [comment]
CLA has been signed by @djalmaaraujo. Bot is wrong.

**Comment by djalmaaraujo** [comment]
@surma I need to add some refactoring to the testes, how should I proceed since this branch is not mine anymore?

**Comment by surma** [comment]
@djalmaaraujo Just re-use your old branch start a new PR. I can close this once your new PR comes in :)

**Comment by djalmaaraujo** [comment]
@surma great. thanks

**Comment by surma** [comment]
Closing this in favor of #1377

**Pull request closed without merging**
