### PR TITLE
End tag of <p> wasn't closed

### PR DESCRIPTION
**Pull request by TristanWiley**

### CODE REVIEW

**Comment by Garbee** [comment]
LGTM but:

1. CLA needs signing
2. Commits need squashing
3. This needs to be PR'ed against the `mdl-1.1` branch in order to make it into the current site and docs.

Thanks and good eyes catching the tag mismatch.

**Comment by TristanWiley** [comment]
I signed it
Also, not used to submitting public Github commits. 3?

**Comment by Garbee** [comment]
Squashing is you need to take these 3 commits and make them into one commit. That way the history is as simple and small as it can be. Ideally one PR = one commit.

Since this needs to go into `mdl-1.1` you are going to need to kill this PR. Then start a new branch based on the `mdl-1.1` branch. Make the appropriate edits in that, then recommit and PR. This time when you are on the page to make the PR, you need to verify you are merging into `mdl-1.1` since `master` is the default. That is the easiest way to handle it.

**Comment by TristanWiley** [comment]
I may have done it wrong, apologies.  https://github.com/google/material-design-lite/pull/4126

**Pull request closed without merging**
