### PR TITLE
Fix tabs memory leak by ensuring a downgrade. Fixes #1803.

### LINKED ISSUE #1803: Investigate upgrade/downgrade leak in MaterialTabs
See the tests merged in #1796

### PR DESCRIPTION
**Pull request by sgomes**
@addyosmani PTAL!

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks Sergio!

**Comment by Garbee** [comment]
We actually do need downgrading. Since event listeners are bound within the component, they need to be unbound. This is simply masking one problem and causing another.

**Comment by sgomes** [comment]
The memory test doesn't indicate any delta in event listeners, @Garbee. Are you sure they're not automatically removed in this situation?

**Comment by Garbee** [comment]
Last I ran tests manually, any event listeners bound to nodes had to be removed from the node before removing the node. Otherwise they lagged around in memory. I can test again to see if things have changed.

**Pull request merged**
