### PR TITLE
Adjust text width on components index

### PR DESCRIPTION
**Pull request by surma**
Follow-up to @santokii comment in #639

### CODE REVIEW

**Comment by santokii** [comment]
Comment: Can we also make the text wrap at 640 width? (currently like 540)

**Comment by addyosmani** [comment]
Currently breaks the build.

**Comment by surma** [comment]
@addyosmani Only the Travis build, not the drone build, which is the canonical one, right? Travis fails because

```
No Rakefile found
```

:wink:

**Comment by crhym3** [comment]
Sorry, don't look at Travis. It's been triggered by a mistake. Drone is the correct one.

**Comment by addyosmani** [comment]
Thanks for confirming. Lgtm to land

**Pull request closed without merging**
