### PR TITLE
🚿 Add component upgrade/downgrade leak tests

### PR DESCRIPTION
**Pull request by samccone**
Looks like a few leaks :)

-------------

**MaterialButton** .. run: 1

node delta | heap delta | event listener
--- | --- | --- |
0|26.09 KB|0

**MaterialSpinner** .. run: 1

node delta | heap delta | event listener
--- | --- | --- |
145|29.78 KB|0

**MaterialTooltip** .. run: 1

node delta | heap delta | event listener
--- | --- | --- |
0|15.17 KB|0

**MaterialDataTable** .. run: 1

node delta :fire: | heap delta | event listener
--- | --- | --- |
5|16.87 KB|0

**MaterialProgress** .. run: 1

node delta | heap delta | event listener
--- | --- | --- |
0|19.95 KB|0

**MaterialRipple** .. run: 1

node delta | heap delta | event listener
--- | --- | --- |
0|26.10 KB|0

**MaterialSnackbar** .. run: 1 

node delta :fire: | heap delta | event listener 
--- | --- | --- |
5|10.95 KB|0

**MaterialTabs** .. run: 1 

node delta :fire:  | heap delta | event listener
--- | --- | --- |
5|16.89 KB|0

### CODE REVIEW

**Comment by jasonLaster** [comment]
:8ball: :bathtub:

**Comment by addyosmani** [comment]
This is awesome work. Thanks so much, @samccone! :fire: @sgomes It may be worth opening individual issues for the leaks against MaterialSpinner, Tabs and so on so we can track them individually.

**Comment by sgomes** [comment]
@addyosmani Yup, I'll take care of that. We should get those fixes in 1.0.6.

**Comment by addyosmani** [comment]
LGTM. Let's do this!

**Pull request merged**
