### PR TITLE
Fix links inside CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by yuyokk**
Hi,

I've gone through the CONTRIBUTING.md and see that some links are broken.
Please check if these changes are appropriate.

Thanks for an awesome library!

### CODE REVIEW

**Comment by Garbee** [comment]
Any reason you closed this? The modifications lgtm.

**Comment by yuyokk** [comment]
My bad, I did not check this PR https://github.com/google/material-design-lite/pull/774
But I can fix few more that are missing inside that PR.

**Comment by Garbee** [comment]
Ah, that isn't a big deal... at least it shouldn't be. Let's see. :smile:

**Comment by Garbee** [comment]
I'll just manually resolve the conflicts myself.

**Comment by yuyokk** [comment]
That makes sense, thank you!

**Pull request merged**
