### PR TITLE
More closure fixes

### PR DESCRIPTION
**Pull request by sgomes**
This PR contains more fixes to help with Closure compiler support, adding fixes necessary to have it not only compile, but run correctly as well. This includes exporting symbols (using the `foo['bar']` syntax), ensuring private properties aren't accessed by outsiders and typing things a bit more strongly in the componentHandler.

All unit tests pass on both compiled and uncompiled code.

@addyosmani @surma PTAL!

### CODE REVIEW

**Comment by Garbee** [comment]
LGTM. I don't see why any supported levels of interaction would break.

**Comment by surma** [comment]
LGTM2 :+1: 

mdlComponentHandler is ridiculous, though ^^

**Comment by sgomes** [comment]
@surma Yup. It's more documentation than code, at this point...

**Comment by surma** [comment]
@sgomes I tried to rebase this against master to pull in @samccone fix (#1571) for `uniffe()` and remove the `$.if`, but I wasn’t sure I wouldn’t be screwing up the PR. It’s on the `surma/more-closure-fixes` branch.

**Comment by sgomes** [comment]
@surma :notes: Don't go breaking my branch... :microphone: 

Ahem. I don't think it's a problem to keep the `$.if` (and this way we'd keep the fixes separate), but if you feel strongly about this let me know and I'll pull in your branch changes.

**Comment by sgomes** [comment]
Actually, given that @samccone's fix is only for `master`, I'm inclined to merge this as-is. You ok with that, @surma?

**Comment by samthor** [comment]
btw, I'm glad this works, but it's clear each export becomes frustratingly verbose. We can probably export everything by default (which is fine, since everything's in self-evaluating etc etc) or use `@export`.

**Comment by samthor** [comment]
I'm happy to look more at this within the next ~24 hours (timezones are hard).

**Comment by surma** [comment]
@sgomes Yeah, of course. Go ahead :)

**Comment by sgomes** [comment]
@samthor I don't think there's a good way to export everything by default, other than using externs. In any case, I'll merge this as-is for now, and we can treat improvements as a new PR, so that we can do further development on Closure tasks and the like in the meantime.

**Pull request merged**
