### PR TITLE
Add tracking to know the amount of visitors with flash enabled.

### PR DESCRIPTION
**Pull request by nicolasgarnier**
r: @addyosmani 

Related to #848

### CODE REVIEW

**Comment by addyosmani** [comment]
I'm blocking on https://github.com/google/material-design-lite/issues/848. Let's manually test the current copy/paste implementation cross-browser to discover where clippy.swf isn't working. 

I don't want to land another beacon to GA if the outcome of 848 is that we need to drop clippy. We already get the UA strings from browsers visiting us through GA today. 

From today:

71% of our visitors are on Chrome, 11% Firefox, 9% Safari, 4% Safari UIWebView/Twitter, 1.47% IE, Opera: 0.81%

**Comment by nicolasgarnier** [comment]
This simply will tell us what amount of users have flash enabled vs. how many have flash disabled and we can't get that through UA strings from browsers (right?). We can then use that to take a simple decision: Is the amount of users who have flash enabled lower than visitors on Chrome? If that's the case we'll get more people to have the copy paste feature by implementing only one (Chrome's) native copy-to-clipboard API.

IMO this can happen in parallel of investigating #848 and knowing what amount of our users have flash (since we use flash on the site) is quite informative. Today we can't take any decision: maybe only 10% of our users have flash or maybe 90%? who knows :D Basically if we can leave this for 30 minutes on the site we'll have the information we need.

Are you manly worried of adding extra analytics calls to the site?

**Comment by sgomes** [comment]
I think in general what we want to measure is not so much who has flash enabled (which may not even be a reliable signal, depending on e.g. how flash blocker extensions are implemented), but rather if the feature works. Sadly, because of the nature of copy to clipboard, we have no automated way of determining that via GA :-/

I think for now it would be best to get in touch with the folks running into issues with the current implementation and asking them to run some tests for us, because I can definitely see clippy not working with some browser/extension/OS combinations, even though it's flash-based.

**Comment by surma** [comment]
What do we do with this? I feel like it’s unneeded by now. I’d vote for discarding.

**Comment by Garbee** [comment]
Doesn't GA already tell you the percentage of your visitors with flash and java (perhaps other plugins)? What is this providing it doesn't already?

**Comment by nicolasgarnier** [comment]
You only get browser/OS and network data in GA afaik. If we can get plugins data I wasn't able to find it :)

I don't really feel this is un-needed. We use Flash on the site and it would be interesting to know what amount of our users (even if it's approximate because of flash blockers) have flash enabled and therefore experience the flash related features. This will also give us the data we need if/when we want to switch from the flash copy-to-clipboard to a native solution (especially since copy-paste is not supported by every browsers natively).

This only gives us extra data :) More data is always good no? :D

**Comment by addyosmani** [comment]
My vote is for discarding :) Primarily because I think that even if we're able to determine Flash enabled user percentage, we won't be able to actionably switch to anything better for at least another year (the native alternatives are still baking and not yet in Edge or Safari). 

That said, I'm happy for @marcacohen to make the final call on this. #848 has already landed and works cross-browser at this point.

**Comment by Garbee** [comment]
https://developers.google.com/analytics/resources/concepts/gaConceptsTrackingOverview

It is in there somewhere.

**Comment by nicolasgarnier** [comment]
Ah yes found it! It's a bit hidden:

Audience > Technologie > Browser & OS > Secondary dimension > Search for "Flash Version"

That;s it! Then we can definitely discard this PR :)

**Comment by nicolasgarnier** [comment]
22.46% Without flash at the moment

**Comment by nicolasgarnier** [comment]
And FYI: Chrome + IE would be 73.5% so we made the right choice (although blindly) using flash to get the most user coverage :D

**Pull request closed without merging**
