### PR TITLE
fix(tabs): Allow tab hrefs to point anywhere

### LINKED ISSUE #4072: Tab navigation for external links is still broken (#1028 #929)
Issues #1028 and #929 still seem to be not properly solved in V1.1.1.
The code seems a little weird. You are adding the EventListener twice. Maybe a merge conflict?

**_layout.js, line 502:_**
```
function MaterialLayoutTab(tab, tabs, panels, layout) {
    /**
     * Auxiliary method to programmatically select a tab in the UI.
     */
    function selectTab() {
        var href = tab.href.split('#')[1];
        var panel = layout.content_.querySelector('#' + href);
        layout.resetTabState_(tabs);
        layout.resetPanelState_(panels);
        tab.classList.add(layout.CssClasses_.IS_ACTIVE);
        panel.classList.add(layout.CssClasses_.IS_ACTIVE);
    }
    if (layout.tabBar_.classList.contains(layout.CssClasses_.JS_RIPPLE_EFFECT)) {
        var rippleContainer = document.createElement('span');
        rippleContainer.classList.add(layout.CssClasses_.RIPPLE_CONTAINER);
        rippleContainer.classList.add(layout.CssClasses_.JS_RIPPLE_EFFECT);
        var ripple = document.createElement('span');
        ripple.classList.add(layout.CssClasses_.RIPPLE);
        rippleContainer.appendChild(ripple);
        tab.appendChild(rippleContainer);
    }
    tab.addEventListener('click', function (e) {
        if (tab.getAttribute('href').charAt(0) === '#') {
            e.preventDefault();
            selectTab();
        }
    });
    tab.show = selectTab;
    tab.addEventListener('click', function (e) {
        e.preventDefault();
        var href = tab.href.split('#')[1];
        var panel = layout.content_.querySelector('#' + href);
        layout.resetTabState_(tabs);
        layout.resetPanelState_(panels);
        tab.classList.add(layout.CssClasses_.IS_ACTIVE);
        panel.classList.add(layout.CssClasses_.IS_ACTIVE);
    });
}
```

Furthermore, **_tabs.js, line 130_** seems missing the === '#' check.

### PR DESCRIPTION
**Pull request by MitchLillie**
* Check for '#' before proceeding with querySelector and tab state modification
* Allows anchors to point to other links

Closes #4072

### CODE REVIEW

**Comment by sgomes** [comment]
Thanks for the PR, @MitchLillie!

@Garbee Do you remember how we had decided to tackle this issue in v1? Does this PR work with that approach?

**Comment by Garbee** [comment]
Unless the tab js is affecting the layout js execution, this has been working as expected for 1.x.

Layout tabs can link to external resources, but internal page content tabs should not. As it is inconsistent if tabs are partially doing live-updating of the DOM and others cause a full page refresh.

This is only for 1.x's lifecycle, though, in 2.x this should change to allow for a comprehensive progressive-enhancement solution to be built by developers.

At this point, we should change in 2.x and as far as I can tell this is not a breaking change for 1.x. So, let's just go ahead and do it. :heavy_check_mark:

**Comment by sgomes** [comment]
Sounds good, thanks @Garbee!

The change looks good to me, let's wait for a successful build and merge. Thanks again, @MitchLillie!

**Comment by MitchLillie** [comment]
Thanks for the comments, all. The tabs in my case are being used with a php framework & router which is very opinionated about the way links are handled; no full-page refresh is actually triggered. Just confirming that this is allowing for an MD-legal use case. :) 

What's up with the build @sgomes ? Anything blocking this on my end?

**Comment by sgomes** [comment]
@MitchLillie Nope, your code is good :) It's just the CI acting up, again... :-/ I'll give this a spin locally when I get a chance instead.

**Comment by Garbee** [comment]
Restarting the build. Looks like a transient error with the memory usage tests.

**Review by jlbyers2869 — APPROVED** [review]

**Pull request merged**
