### PR TITLE
Use percentage function for computing percentage on grid

### PR DESCRIPTION
**Pull request by nkpgardose**
Reference: http://sass-lang.com/documentation/Sass/Script/Functions.html#percentage-instance_method

### CODE REVIEW

**Comment by ZakariaRidouh** [comment]
Great idea, but how is this any different than how it was done before?

**Comment by nkpgardose** [comment]
@ZakariaRidouh Nothing much. I did compare it to the previous percentage implementation and it produces same result.

**Comment by Garbee** [comment]
-1 to changing this. It isn't providing any useful benefit.

Also for 2.x we are working on reducing our Sass usage to only what we *really* need to provide maintainability benefits to the project. This isn't changing maintainability at all but instead locking us into more Sass functions.

**Comment by nkpgardose** [comment]
@Garbee I'll be closing this PR. Good to hear 2.x are reducing Sass usage.

**Pull request closed without merging**
