### PR TITLE
Update gulp-sass version.

### PR DESCRIPTION
**Pull request by Garbee**
Upgrading sass builder to try and fix some reports of builds breaking. Issue #1118 for instance.

### CODE REVIEW

**Comment by addyosmani** [comment]
@zeakd could you try this out?

**Comment by Garbee** [comment]
@addyosmani From their report:

> I changed to same gulp-sass version of your project ( ^2.0.4 -> ^1.3.3 ) and it works. 

I just changed from ^ on the start to an * on the patch to make sure we only update within patch releases. Minor updates we should re-assess in case of accidental breakage.

**Comment by addyosmani** [comment]
@Garbee Thanks. I missed that in the original report. Manually verifying locally.

**Comment by Garbee** [comment]
OH wait, I misread the arrow direction.

They are using 2.0.4 in *their* project and it was breaking on them. #1075 may have fixed the problems with 2.0.4, so the master will work but 1.0.0 tag still won't.

Either way though, if 2.x works now we should go with it since it does lead to a faster build (plus new goodies.)

**Comment by addyosmani** [comment]
Works for me locally. Regarding the tag: we're hopefully going to tag and publish 1.0.1 this week. @surma can we get a second verification from you that this doesn't cause any breakage?

**Comment by surma** [comment]
On it

**Comment by surma** [comment]
`npm install` on node 0.12 only worked for me after I added `phantomjs` explicitly to `package.json`. Added a commit for that.

Microsite, components and templates look fine. 

We are breaking node 0.10 btw, which I *think* we used to platform on. 
```
$ gulp serve
...
Error: `libsass` bindings not found in /Users/surma/src/github.com/google/Material-Design-Lite/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-14/binding.node. Try reinstalling `node-sass`?
```
Is node 0.10 still relevant? If not, LGTM.

**Comment by Garbee** [comment]
Ah, the phantom thing may have been what others were hitting as well. The install/updates worked for me (aside from once), then again I could have had a cache somewhere.

Node 0.10 is years old. Good to not support imo. Whether it is in LTS repos or not, NVM should be used to manage and keep node updated.

**Comment by Garbee** [comment]
P.S. Googlebot is drunk again.

**Comment by surma** [comment]
> Node 0.10 is years old. Good to not support imo.

Agreed. Good to merge, imo.

**Comment by Garbee** [comment]
Assigning to Addy for a quick review and merge of he agrees with us dropping 0.10 support.

**Comment by addyosmani** [comment]
Current Node is `0.12.7` and 0.10.x is pretty old at this point. I did have a question around us opting for 2.0.* vs ^2.0.0, but @Garbee already included a comment about that. Before we merge this, two things:

* Can we verify via VM that this will build on Windows 8.1/10 (per #1089) 
* Please include a note in the README calling out that Node 0.12.x will be required to build the source

**Comment by Garbee** [comment]
I'll handle it. I can test windows 10 on actual hardware, 8.1 in a vm. A quick note on this should be simple as well.

**Comment by Garbee** [comment]
Just added a quick blockquote, "MDL requires NodeJS 0.12." underneath the "npm install" step of the instructions. Direct in point and focused where developers building will be looking.

**Comment by surma** [comment]
:+1:

**Comment by Garbee** [comment]
FYI, found [this issue](https://github.com/nathanboktae/mocha-phantomjs/issues/167) on mocha-phantomjs's repo as to why the peerdep change occured. Maybe someone who knows that aspect better can look through real quick and see if there is anything we could improve with our package requirements around it.

**Comment by Garbee** [comment]
I'll dig into that issue actually. The phantomjs version specified is not satisfying the dependency.

And here we go down the rabbit hole!

**Comment by Garbee** [comment]
So, seems to work fully on Mac and Linux. It is Windows where we are having problems. But, those don't seem to be related to *this* update, but instead some phantomjs stuff that happened last week.

This patch functions and is good to merge. We should assess windows breakage on its own since that seems unrelated.

**Comment by surma** [comment]
Agreed.

**Comment by addyosmani** [comment]
I'm starting to get more direct reports of the PhantomJS issue arising. Looking at https://github.com/google/material-design-lite/commits/master/package.json, I can't see what could have caused this other than an upstream dep issue @Garbee mentioned.

**Pull request closed without merging**
