### PR TITLE
Replaced dead link

### PR DESCRIPTION
**Pull request by nextlevelshit**

### CODE REVIEW

**Comment by nextlevelshit** [comment]
I won't sign it!

**Comment by Garbee** [comment]
If you refuse to sign the CLA then you might as well not send in any additional PR's. As explained in Issue #866 we are unable to accept anything, even adding a period into documentation, without a signed CLA.

Thank you for trying to help, but we can't ignore the CLA.

**Comment by nextlevelshit** [comment]
Yep, I got it. Just tried to help. But I'm still not a b*** ... Just read this:

```[...] You hereby grant to Google [...] a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare derivative works of, publicly display, publicly perform, sublicense, and distribute Your Contributions and such derivative works.```

So I would work for a corporation without any salary. That is in fact not in the sense of open-source my dear friends. :-1:

**Comment by pguth** [comment]
@nextlevelshit Your work would fall under apache-2 license anyway. That makes it kind of no big deal to sign such legal gibberish. Let's this discuss that over a beer some time! I would like that!

**Comment by nextlevelshit** [comment]
Yes, please explain it to me. I would be glad :+1:

**Pull request closed without merging**
