### PR TITLE
Fix #1335

### LINKED ISSUE #1335: The animation on tabs is wrong
Sometimes (quite often actually), the animation on the tab bar is not correct. Most the the times, the blue underline appear, quickly disappear and re-appear with the animation.

tabs

### PR DESCRIPTION
**Pull request by zcyzcy88**

### CODE REVIEW

**Comment by zcyzcy88** [comment]
I signed it!

**Comment by Garbee** [comment]
LGTM

**Comment by Garbee** [comment]
cc @sgomes for a sanity check on this one too.

**Comment by sgomes** [comment]
Good catch, thanks @zcyzcy88!

**Pull request merged**
