### PR TITLE
Updated the H5BP reset file

### PR DESCRIPTION
**Pull request by Ninir**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #1350 (minification issue with YUICSS/UglifyCSS)

This updates the `_h5bp.scss` file to match the latest version from https://github.com/h5bp/html5-boilerplate.

### CODE REVIEW

**Comment by surma** [comment]
Code LGTM. Gonna wait for @sgomes to ACK before merging.

**Comment by surma** [comment]
All looks good, thanks @Ninir  :)

**Comment by sgomes** [comment]
(I acked OOB :+1: )

**Comment by Ninir** [comment]
Thank you guys! :+1:

**Pull request merged**
