### PR TITLE
Remove import of partials from components

### PR DESCRIPTION
**Pull request by JacobDorman**
per #1474 import of _variables and _mixins directly into component's prevents customisation outside the framework.

There's probably still some things to look at, (functions and color definitions), but the tests all pass.

Can add !default to variables where it is missing too, if this gets the green-light.

### CODE REVIEW

**Comment by JacobDorman** [comment]
I signed it!

**Comment by surma** [comment]
Code LGTM, local tests suggests it works as well :smile: Thanks for your work, @JacobDorman.

I will hold off on a merge until we determine wether this is considered a BC and therefore is v1.1 or v2

**Comment by surma** [comment]
@JacobDorman We came to the conclusion that we have to consider SemVer for SASS files. Therefore, we cannot merge this before we have merge window for v2.

**Comment by JacobDorman** [comment]
No problem, I guess it could break BC if someone has overridden variables/mixins but is relying on them being reinstated later.

Adding !defaults to more of the variables should be safe though? (#1525)

**Comment by webmaven** [comment]
Perhaps there should be a v2 branch that this PR can be merged into?

**Comment by surma** [comment]
@webmaven It’s too early to start any work regarding v2. And I think we’d rather do the same thing we did for v1.1, where `master` is the current version (in that case, v2) and have a “legacy” branch.

We are actively collecting open PRs :wink:

**Comment by webmaven** [comment]
:+1:

**Comment by sgomes** [comment]
No longer works with our codebase, sorry! But I'm happy to say this is definitely something we'll be working on with v2!

**Pull request closed without merging**
