### PR TITLE
Add !default to sass variables so they can be overridden

### PR DESCRIPTION
**Pull request by JacobDorman**

### CODE REVIEW

**Comment by surma** [comment]
Thanks for the PR, @JacobDorman!

I believe there was a reason we stopped adding `!default`, but I can’t remember. Only #864 comes to mind. @Garbee @sgomes What’s your take on this?

**Comment by sgomes** [comment]
The problem with adding `!default` to all properties is that it may give the wrong impression that everything will work nicely even if you change those values, whereas that's not the case with a lot of properties. Sizes are very easy to shoot yourself in the foot with, for example, causing subtle alignment issues that may be hard to find.

I'm ok with adding `!default` to every property, as long as we make it clear somehow that modifying these will likely break components in subtle or not-so-subtle ways.

**Comment by surma** [comment]
Alright, I will merge this and a comment to `_variables.scss`. Thanks again, @JacobDorman!

**Comment by JacobDorman** [comment]
that's a good point @sgomes. I left out the variables that were calculated from other variables because i was thinking along those lines. 

I can see the motivation for setting things up this way. Explicitly importing dependencies into each component to makes them more modular and encapsulated, and it's becoming more popular with tooling that lazy-loads or asyncs components.

But for a framework/library in a language without much in the way of abstraction concepts it leaves the only solution private forking, or just copy-and-override, which isn't ideal.

Opinioned frameworks are ideal starting points, but I want to be able to adjust/override those opinions  when necessary, without losing the venerable upstream :)

**Pull request merged**
