### PR TITLE
Fix tooltip position

### PR DESCRIPTION
**Pull request by yuyokk**
Hi,

As I see there is some problem with tooltip positioning if the element is close to the left side.
Please see the picture with the problem.

I've applied some patch for the issue (the picture on the right shows the tooltip with the patch applied). 

tooltip

Please check it.
Thanks

### CODE REVIEW

**Comment by Garbee** [comment]
lgtm

**Comment by nicolasgarnier** [comment]
Looks great (I've been meaning to file an issue for this for a while :)

Ideally we should also handle the other cases at some point. If not in this commit then lets file an issue for sure:
 - If the tooltip overflows on the right side of the screen.
 - If the tooltip overflows on the bottom of the screen.

**Comment by addyosmani** [comment]
@nicolasgarnier Would you like to go ahead and paste your text from above into a new issue and we can tackle that after?

@yuyokk Testing now. Thanks for the PR!

**Comment by addyosmani** [comment]
lgtm

**Comment by nicolasgarnier** [comment]
done! tracked in #858

**Pull request closed without merging**
