### PR TITLE
Fixes errors and omissions in existing layout docs. Fixes #1310

### LINKED ISSUE #1310: Thoroughly review and fix layout docs
There have been several instances of layout documentation being incorrect (e.g. #1294 and #1289).

### PR DESCRIPTION
**Pull request by sgomes**
@surma PTAL!

### CODE REVIEW

**Comment by surma** [comment]
Well, looking at the code, it’s obvious you introduced a new memory leak in the menu component. Lol.

Code LGTM. Merge at will :)

@crhym3 @samccone Any idea why the memory test is failing?

**Comment by crhym3** [comment]
Technically, it's failing on this line in [test/memory/test.js](https://github.com/google/material-design-lite/blob/87368f406c10f7d9b899b7d37def3fcdb038d19b/test/memory/test.js#L28):

```js
assert.equal(true, after.jsEventListeners <= initial.jsEventListeners);
```

"That's all we know" :tm:

**Comment by sgomes** [comment]
Thanks for the review, @surma! I'll merge this PR now, so you may want to open a new issue if the memory test failure persists.

**Comment by samccone** [comment]
Initially I think it could be a few things.

1. There is a newer version of chrome which is behaving differently
2. The memory tests are not consistent with one pass.

**Comment by crhym3** [comment]
FYI you can see chrome version in the build log:

```
Unpacking google-chrome-stable (44.0.2403.130-1) over (44.0.2403.130-1) ...
Setting up google-chrome-stable (44.0.2403.130-1) ...
```

**Comment by surma** [comment]
Just had Drone run again. Now the test passes. So we might still have some weird inconsistency, @samccone.

If Drone fails, just look at the log. If it’s the memory test failing, rerun the build and see if it persists. @samccone and I will try to figure this out :)

**Comment by crhym3** [comment]
second drone build resulted in

```
event listener delta: -2
```

yes it is

**Pull request merged**
