### PR TITLE
Fix Menu's list width.

### PR DESCRIPTION
**Pull request by sika-uma**
To undisplay horizontal scroll bar on Left Menu at following page.
http://www.getmdl.io/templates/dashboard/index.html

### CODE REVIEW

**Comment by sika-uma** [comment]
英語わからない T-T

**Comment by Garbee** [comment]
This is a second  possible resolution to the same  thing  PR #1022 is trying to address. However,  both still depend upon the primary issue #994 to be fully triaged before deciding on a fix plan.

**Comment by surma** [comment]
> 英語わからない T-T

“do not know English”


@sika-uma [Google Translate](https://translate.google.com/#en/ja)?

**Comment by sika-uma** [comment]
When I do not want to input a phone number and an address, what should I do?
I think this request is not necessary now. If not necessary, please be closed.

**Comment by surma** [comment]
@sika-uma We need all information for the CLA. This has legal reasons. We can’t do anything about that. Sorry.

**Comment by sika-uma** [comment]
Thanks.
I'm satisfied that the bug's revised.

**Pull request closed without merging**
