### PR TITLE
safari layout scrolling issue workaround

### PR DESCRIPTION
**Pull request by oddui**
Ref https://github.com/google/material-design-lite/issues/2559#issuecomment-168875182

### CODE REVIEW

**Comment by Garbee** [comment]
I guess since this is only an issue on Safari then the PR will work fine. But, it will only work on 9 according to [caniuse](http://caniuse.com/#feat=page-transition-events).

One hell of a hack for no good reason. Safari still needs a bug report since this at least shows where the issue is coming from.

**Comment by surma** [comment]
I wouldn’t mind merging this in to have layout behave better for the rest of 1.x. Well have to give this a thorough cross-browser check, though.

**Comment by oddui** [comment]
@Garbee if you click 'showing all' in your link, it'll show green on safari 5+

**Comment by Garbee** [comment]
ah, 5+ cool then. MDN should get updated too... My laptop browser was kicking out on me and nothing would load on the site earlier.

For clarity, my "no good reason" is just anguish that Safari does this. It wasn't like we shouldn't include it. We should since clearly there is an issue in Safari and as long as this doesn't have any side affects, it's all cool. I just can't test since I don't have Safari.

**Comment by Garbee** [comment]
@surma Mind trying to test this to get it in before 1.1 is tagged? Would be a nice addition and looks like we didn't tag before the cleansing meeting last week.

**Comment by surma** [comment]
Closed in favor of #4010

**Pull request closed without merging**
