### PR TITLE
Fixing up indentation issues that prevented jshint from successfully …

### PR DESCRIPTION
**Pull request by gauntface**
…running

Just indentation changes.

### CODE REVIEW

**Comment by surma** [comment]
Thank you :)

**Comment by Garbee** [comment]
LGTM.

How did this pass the code style check though on drone when the PR was made? Looks like we may have a tooling flaw.

**Comment by addyosmani** [comment]
LGTM2. I was surprised this wasn't caught earlier too.

**Comment by surma** [comment]
The original PR has a "1 test passed" (the CLA), which would imply that there was 1 failing. I am pretty sure I’d never press the merge button without all the tests passing, but maybe I screwed up.

**Pull request merged**
