### PR TITLE
Add 'Showcase' section to the site

### PR DESCRIPTION
**Pull request by addyosmani**
Preview:

screen shot 2015-10-30 at 13 19 20

Images have already been run through ImageOptim.

### CODE REVIEW

**Comment by samccone** [comment]
@addyosmani ladies and gents :clap:

**Comment by samccone** [comment]
:+1: lgtm

**Comment by addyosmani** [comment]
@sgomes any opposition to landing this?

**Comment by sgomes** [comment]
Nope, LGTM. Thanks,@addyosmani!

**Comment by addyosmani** [comment]
:sake:

**Pull request merged**
