### PR TITLE
Set cursor to default on disabled button

### PR DESCRIPTION
**Pull request by faergeek**

### CODE REVIEW

**Comment by faergeek** [comment]
Okay

**Comment by faergeek** [comment]
Something wrong with build server?

**Comment by crhym3** [comment]
build server is fixed now.

**Comment by surma** [comment]
Thanks @crhym3 for fixing.

Code LGTM, thanks @faergeek :)

**Comment by faergeek** [comment]
It was too easy :-)
I'm more interested in my second PR

**Comment by sgomes** [comment]
LGTM, but we should probably be merging this into `mdl-1.0` rather than `master`. I'll see if I can take care of that without asking you for a new PR :)

**Comment by sgomes** [comment]
Merged into `mdl-1.0` (thanks for the tip on how to do it with `hub`, @surma!)

**Pull request closed without merging**
