### PR TITLE
Cleanup docs

### PR DESCRIPTION
**Pull request by Garbee**
Remove duplicate blocks. Add newline after headings.

### CODE REVIEW

**Comment by surma** [comment]
Thanks for Re-PR-ing! LGTM

**Comment by Garbee** [comment]
Once again, flaky memory test. Can it be manually retriggered? (Trying a force push back to the branch with nothing to see if that works.)

**Comment by samccone** [comment]
@Garbee looks like the last error was not a memory flake

**Comment by Garbee** [comment]
@samccone Yea, the one that just ran was a phantomjs download fail (403). The one previously stopped at the command running the memory test.

**Comment by samccone** [comment]
weird, feel free to ping me on any flake are memory tests :)

**Pull request merged**
