### PR TITLE
Fix BEM naming in progress

### PR DESCRIPTION
**Pull request by Garbee**
Change the intermediate progress class to use a modifier instead of a block.

### CODE REVIEW

**Comment by surma** [comment]
We can’t remove the ill-named classes for 1.1, can we? We have to keep both, like we did for layout.

**Comment by Garbee** [comment]
Yup, can't remove it due to BC. Which is fine, 2.x is right after so the duplicate problem will be short-lived.

**Comment by surma** [comment]
Oh lols, I looked at the doc fixes only and thought you *did* remove the old classes. My bad. LGTM :)

**Comment by Garbee** [comment]
Yea, docs are updated to only show the new to encourage it gets used going forward.

**Pull request merged**
