### PR TITLE
Match shadow opacity and ordering to polymer example.

### PR DESCRIPTION
**Pull request by gcallaghan**
see https://github.com/PolymerElements/paper-styles/blob/master/shadow.html for comparison

### CODE REVIEW

**Comment by addyosmani** [comment]
Hmm. I just compared our current shadows to the ones used internally at Google for apps implementing Material Design and they match. @shyndman would you happen to know whether the Polymer or MDL shadows are more reflective of the current correct values? Would love to align.

**Comment by addyosmani** [comment]
friendly ping @shyndman

**Comment by webmaven** [comment]
@addyosmani, perhaps another ping?

**Comment by shyndman** [comment]
Looks like [Polymer went rogue](https://github.com/PolymerElements/paper-styles/commit/6059261ad910e6847fe4ed73be35d55bd453c159). I'll follow up.

**Comment by addyosmani** [comment]
We appreciate you chasing it up, @shyndman. Thank you. We'll update whatever we need to on our end once we hear back from you.

**Comment by Garbee** [comment]
Seems to me like this isn't something we need to fix. If Polymer is the only odd-duck and the spec hasn't changed, we are good. Polymer should be the ones to revert the edit causing them to not align.

**Pull request closed without merging**
