### PR TITLE
Add note to grid about specificity of selectors.

### PR DESCRIPTION
**Pull request by Garbee**
Quick comment in source about specificity. Hopefully will stop PRs and confusion from coming in that change the specificity by trying to "fix" the code.

cc @surma

### CODE REVIEW

**Comment by Garbee** [comment]
P.S. Drone is drunk. :dancer:

**Comment by surma** [comment]
Nope, it’s not. Can’t compile locally, either. Not sure what exactly is going on, but `node-sass` doesn’t seem to like the comment you added.

**Comment by surma** [comment]
Apparently, `node-sass` is trying to compile the example in your comment. Couldn’t find an existing issue related to this. I’d say just remove the example.

**Comment by Garbee** [comment]
Oh, maybe it is the backticks since ES6 has some support for that... Very odd.

**Comment by surma** [comment]
No, backticks are not the issue, I tried that. It’s about `$i` which is undefined at the point of the comment.

**Comment by Garbee** [comment]
ah ok. Just got back over to Linux. I'll probably just modify the `$i` to an actual value. That should be good enough.

**Comment by surma** [comment]
Thanks, @Garbee :) (Didn’t notice you added the commit already, are there notifications for commits in PRs?!)

**Comment by Garbee** [comment]
No notifications for when you force push an amended commit. I'll try to remember to ping the next time. ;)

**Pull request merged**
