### PR TITLE
Removed uneeded icon class from badge demos.

### LINKED ISSUE #998: Example code in the Badges documentation referencess an unused "icon" class
In the [badges documentation](http://www.getmdl.io/components/index.html#badges-section) there's the following example:
```
<!-- Number badge on icon -->
<div class="icon material-icons mdl-badge" data-badge="1">account_box</div>
<!-- Icon badge on icon -->
<div class="icon material-icons mdl-badge" data-badge="♥">account_box</div>
```
It applies the ```icon``` class, however this class isn't used in the CSS. I'm presuming this is a mistake and should be removed from the example?

### PR DESCRIPTION
**Pull request by Garbee**
Fixes #998

### CODE REVIEW

**Comment by Garbee** [comment]
Assigning Addy since this should be  quick & simple review.

**Comment by addyosmani** [comment]
lgtm

**Comment by addyosmani** [comment]
I am Mr. quick and simple :)

**Comment by Garbee** [comment]
insert obligatory "That's what she said". FTR, you asked for it.

**Pull request closed without merging**
