### PR TITLE
Textfield can autofocus.

### LINKED ISSUE #1125: autofocus attribute doesn't work
autofocus native HTML5 attribute doesn't work with material-design-lite

### PR DESCRIPTION
**Pull request by Garbee**
fixes #1125

### CODE REVIEW

**Comment by Garbee** [comment]
@samccone Can you help figure this one out? On drone, build fails on the new test. But locally, it works just fine. No clue why unless the drone environment is running differently than local, which it still shouldn't be.

success

**Comment by Garbee** [comment]
ah,just realized I need to run `gulp scripts && gulp mocha`. For some reason mocha is  only rebuilding styles (which seem irrelevant) and not scripts. Will file another bug on this one.

**Comment by sgomes** [comment]
Works in Chrome and IE. LGTM, merge at will!

**Comment by aminy** [comment]
This seems to break the build: https://ci.cloudware.io/google/material-design-lite/47

**Comment by Garbee** [comment]
@aminy We know. It was because I worked on two separate PRs that needed the same thing and didn't catch it. So I ended up duplicating something. PR #2016 is open to fix the problem.

**Comment by aminy** [comment]
@Garbee  Thanks a lot.

**Pull request merged**
