### PR TITLE
Remove XHTML slashes

### PR DESCRIPTION
**Pull request by surma**
As discussed in #1650 with @sindresorhus

### CODE REVIEW

**Comment by Garbee** [comment]
lgtm

**Comment by sindresorhus** [comment]
There are more instances of XHTML slashes. Try grepping for `"/>"` ;)

**Comment by sindresorhus** [comment]
Here's the places that needs fixing:

```
docs/_templates/layout.html
30:    <link rel="shortcut icon" href="{{page.include_prefix}}assets/favicon.png" />

src/checkbox/snippets/check-off.html
2:  <input type="checkbox" id="checkbox-2" class="mdl-checkbox__input" />

src/checkbox/snippets/check-on.html
2:  <input type="checkbox" id="checkbox-1" class="mdl-checkbox__input" checked />

src/icon-toggle/snippets/icon-off.html
2:  <input type="checkbox" id="icon-toggle-2" class="mdl-icon-toggle__input" />

src/icon-toggle/snippets/icon-on.html
2:  <input type="checkbox" id="icon-toggle-1" class="mdl-icon-toggle__input" checked />

src/layout/snippets/fixed-header-drawer.html
16:                 id="fixed-header-drawer-exp" />

src/layout/snippets/waterfall-header.html
23:                 id="waterfall-exp" />

src/radio/snippets/radio-off.html
2:  <input type="radio" id="option-2" class="mdl-radio__button" name="options" value="2" />

src/radio/snippets/radio-on.html
2:  <input type="radio" id="option-1" class="mdl-radio__button" name="options" value="1" checked />

src/slider/snippets/demo.html
4:        min="0" max="100" value="0" tabindex="0"/>
8:        min="0" max="100" value="10" tabindex="0"/>

src/slider/snippets/slider-default.html
3:  min="0" max="100" value="0" tabindex="0"/>

src/slider/snippets/slider-starting-value.html
3:  min="0" max="100" value="25" tabindex="0"/>

src/switch/snippets/switch-off.html
2:  <input type="checkbox" id="switch-2" class="mdl-switch__input" />

src/switch/snippets/switch-on.html
2:  <input type="checkbox" id="switch-1" class="mdl-switch__input" checked />

src/textfield/snippets/textfield-expanding.html
8:      <input class="mdl-textfield__input" type="text" id="sample6" />

src/textfield/snippets/textfield-floating-numeric.html
4:    <input class="mdl-textfield__input" type="text" pattern="-?[0-9]*(\.[0-9]+)?" id="sample4" />

src/textfield/snippets/textfield-floating-text.html
5:    <input class="mdl-textfield__input" type="text" id="sample3" />

src/textfield/snippets/textfield-numeric.html
4:    <input class="mdl-textfield__input" type="text" pattern="-?[0-9]*(\.[0-9]+)?" id="sample2" />

src/textfield/snippets/textfield-text.html
4:    <input class="mdl-textfield__input" type="text" id="sample1" />

test/index.html
9:  <link rel="stylesheet" href="../dist/material.css"/>

templates/article/index.html
40:    <link rel="shortcut icon" href="images/favicon.png" />
74:              <input class="mdl-textfield__input" type="text" id="search" />

templates/blog/index.html
40:    <link rel="shortcut icon" href="images/favicon.png" />

templates/dashboard/index.html
40:    <link rel="shortcut icon" href="images/favicon.png" />
74:              <input class="mdl-textfield__input" type="text" id="search" />
166:                      <input type="checkbox" id="chkbox1" class="mdl-checkbox__input" />
172:                      <input type="checkbox" id="chkbox2" class="mdl-checkbox__input" />
178:                      <input type="checkbox" id="chkbox3" class="mdl-checkbox__input" />
184:                      <input type="checkbox" id="chkbox4" class="mdl-checkbox__input" />

templates/android-dot-com/index.html
59:              <input class="mdl-textfield__input" type="text" id="search-field" />

templates/text-only/index.html
40:    <link rel="shortcut icon" href="images/favicon.png" />
```

**Comment by surma** [comment]
Lol. My editor failed me. Thanks for keeping an eye out, @sindresorhus.

**Comment by sindresorhus** [comment]
Would recommend https://github.com/ggreer/the_silver_searcher ;)

**Comment by surma** [comment]
@sindresorhus It is done!

Local testing suggests everything remains functional.

@Garbee Pls Re-ACK, if you find the time.

**Comment by Garbee** [comment]
LGTM merge at will once drone passes.

**Comment by addyosmani** [comment]
LGTM2. Drone appears to be passing here now.

**Pull request merged**
