### PR TITLE
Add touch delay negation for mobile IE. Misc cleanup.

### LINKED ISSUE #893: Negate touch delay
Is there the old 300 ms lag on touch devices?

Seems I get a better response on touch devices when testing with fastclick.
Most libraries take care of this nowadays already, so was expecting MDL to do so, too.

### PR DESCRIPTION
**Pull request by Garbee**
Fixes #893 as far as code goes.

### CODE REVIEW

**Comment by surma** [comment]
Thanks, @Garbee! This will need extensive testing across all platforms to ensure there’s no unexpected interference with ripples and similar stuff.

**Comment by Garbee** [comment]
I can handle FF, Chrome (Desktop and Android 5.1), and IE (desktops) testing tomorrow. Someone else will need to handle Apple stuff since I don't have any access to their software/hardware.

**Comment by surma** [comment]
No problem, I can do that.

**Comment by addyosmani** [comment]
I'll also help with device testing. Thanks for working on this!

**Comment by surma** [comment]
All browsers seem to work fine. Physical iOS and Android seem to play along as well. 
If this passes @addyosmani’s Surface test, it’s good to merge imo.

**Comment by Garbee** [comment]
Whoops, sorry I forgot to handle testing myself. Got caught up in Snackbar testing and now writing new unit tests for the component handler. Thanks for covering it guys!

**Comment by addyosmani** [comment]
Tested here too. LGTM for landing.

**Pull request closed without merging**
