### PR TITLE
Make labels interact better with placeholders in textfields. Fixes #243.

### LINKED ISSUE #243: Textfield label overlaps if input has placeholder
The textfield (at least with a single-line) doesn't look right at all if you give the input a placeholder.

For example:
```html
<div class="mdl-textfield mdl-js-textfield">
            <input class="mdl-textfield__input" type="email" id="email" name="email" placeholder="you@example.com" required>
            <label class="mdl-textfield__label" for="email">Email:</label>
        </div>
```

This provides a display where the placeholder overlaps the label making both unreadable. Placeholders are pretty common when you are expecting a specific format within a text area to show a user how to enter something. While pattern matching and such do work, placeholders are effective in portraying what is requested ahead of time.

Anything we can do here considering the [spec on Text Fields](http://www.google.com/design/spec/components/text-fields.html) makes no mention of placeholders?

### PR DESCRIPTION
**Pull request by sgomes**
@surma PTAL!

### CODE REVIEW

**Comment by surma** [comment]
Code LGTM. Does this mean that we are prioritizing placeholders of our own labels?

**Comment by sgomes** [comment]
Yes, intentionally. None of our snippets use placeholders, so if people have gone out of their way to add them, we assume they know what they're doing.

**Comment by surma** [comment]
Because alternatively, we could do

```CSS
::-webkit-input-placeholder,
::-moz-placeholder,
:-ms-input-placeholder {  
   color: rgba(0, 0, 0, 0);
}
```

**Comment by surma** [comment]
Okay, merge at will :)

**Comment by sgomes** [comment]
Thanks, @surma! :)

**Pull request merged**
