### PR TITLE
fix ripple.js bug

### PR DESCRIPTION
**Pull request by hanyuzhou2006**
when the clientX or clientY value is 0 , it will be wrong!

### CODE REVIEW

**Comment by hanyuzhou2006** [comment]
I signed it!

**Comment by MA-Maddin** [comment]
why `event.clientX !== undefined` over `event.clientX != null` ?
what if event.clientX is null?

**Comment by hanyuzhou2006** [comment]
see this code:
 var clientX = event.clientX ? event.clientX : event.touches[0].clientX;
if event.clientX ===0 ,clientX value will goes to event.touches[0].clientX,but this time event.touches is undefined

**Comment by sgomes** [comment]
Thanks, @hanyuzhou2006! LGTM, as I don't think `clientX` and `clientY` can ever be null.

**Comment by hanyuzhou2006** [comment]
undefined == true is true

发自我的 iPhone

**Comment by hanyuzhou2006** [comment]
it was an unnormal pull request

发自我的 iPhone

**Pull request merged**
