### PR TITLE
[infrastructure] Configure ESLint, fix any existing errors

### PR DESCRIPTION
**Pull request by traviskaufman**
Additional work:

* Add postinstall command which runs `lerna bootstrap`

Part of #4464

### CODE REVIEW

**Comment by traviskaufman** [comment]
@Garbee @rfru PTAL?

**Comment by Garbee** [comment]
I'll test this in a minute. Want to verify the eslint to yaml conversion doesn't mess up some editor linters.

**Comment by Garbee** [comment]
VSCode and PHPStorm/WebStorm both work with the yaml so LGTM.

Just wondering though, why switch to YAML for the configuration anyways? Is it providing any benefit?

**Comment by traviskaufman** [comment]
@Garbee I like yaml because it has comments which means you can justify decisions you make in the configs :)

**Comment by rfru** [comment]
LGTM

**Pull request merged**
