### PR TITLE
feat(examples): add VueJS 2.0 example with checkboxes.

### PR DESCRIPTION
**Pull request by petejohanson**
* Add basic VueJS components for Checkbox, CheckboxLabel,
  and CheckboxWrapper.
* Add a simple app that shows usage, binding props, events, etc.

### CODE REVIEW

**Comment by traviskaufman** [comment]
Wow! You rock! Thanks so much for taking the time to put this together. LGTM

**Comment by sgomes** [comment]
Holy 🐮 , this is amazing, @petejohanson! Thanks so much for putting this together!

I'd love to hear if you had any problems with either the docs or the code, or any suggestions you might have. We didn't really expect anyone digging in as deep as this before alpha :D

LGTM for merge :)

**Comment by petejohanson** [comment]
In general, the object composition approach seems nice to me. Having the default adapter as an 'API guide ' was nice, but obviously some more docs on the adapter APIs as V2 matures will be beneficial.

I really want to work on updating this with the latest VueJS 2.0 SSR integration, since that is the one area that isn't clear yet to me what tweaks to the current code would be needed (and seems like with the nice V2 design here will work, once done right).

Looking forward to seeing this progress!

**Comment by sgomes** [comment]
Thanks for the comments, @petejohanson!

Yep, we definitely have plans to document things a bit more thoroughly. @traviskaufman has given it a good start [on this thread](https://github.com/google/material-design-lite/issues/4578#issuecomment-241897131), but we need to move it somewhere less ephemeral.

I'm really looking forward to your future experiments!

**Pull request merged**
