### PR TITLE
Ripple effect inspired by Angular Material

### PR DESCRIPTION
**Pull request by kybarg**
Added new animation timing function and smooth ripple effect.

### CODE REVIEW

**Comment by Garbee** [comment]
lgtm. I like the slower timing.

For the record, just because Angular's implementation was early does not mean it is the spec. I don't want a precedent set that Angular is the standard implementation and we should align with that. Not that this is directly advocating that is the case, just being clear in case anyone wants to reference this later.

**Comment by kybarg** [comment]
@Garbee Thanks) Just noticed it is closer to MD animations suggestion https://www.google.com/design/spec/components/buttons.html#buttons-flat-raised-buttons ("Buttons in motion" section) I'm not going to take Angular Material as reference cause it has own deviations from MD spec.

**Comment by addyosmani** [comment]
@kybarg would you mind staging your change on codepen (or somewhere else) and I'll make sure we have the MD team review early this week so we can make a call on this? Fwiw, I prefer your changes too.

**Comment by kybarg** [comment]
@addyosmani Happy to help http://kybarg.github.io/mdl-showcase/components/index.html

**Comment by addyosmani** [comment]
Fwiw, we're discussing this with the team and are still waiting on their feedback. Will update the bug once that's done.

**Comment by surma** [comment]
@addyosmani What is the latest news on this?

**Comment by addyosmani** [comment]
We were told that the latest spec is correct and we should follow it's suggestions on ripples vs. what any particular implementation has opted for.

**Comment by surma** [comment]
Closing this then. Thanks for your work, though, @kybarg!

**Pull request closed without merging**
