### PR TITLE
Making shadow declarations consistent between elevations 0 and 24.

### PR DESCRIPTION
**Pull request by sgomes**
Also adds missing elevations.

@Garbee or @surma: PTAL!

### CODE REVIEW

**Comment by Garbee** [comment]
Where are these missing elevations specified for use/construction? I don't recall ever seeing where they are necessary somehow. We shouldn't include extra things like this without a clear use-case imo. It isn't keeping things lite.

Also, `0dp`... Isn't that just `box-shadow:none;`? Where does adding this one in particular provide benefit?

**Comment by sgomes** [comment]
We're adding the different elevations because due to guidance from the MD team. Apparently, they should all be available, even though only a few examples are shown on the spec. They provided an algorithm to calculate the intermediate heights, as well as the full output of running that algorithm, which I used to create all the mixins.

You're right about the `0dp` elevation; the numbers there were to make the calculation easier, but implementation-wise it makes more sense to have it as `none`. Made that change

**Comment by Garbee** [comment]
AH ok, thanks for explaining why they are needed.

LGTM.

**Comment by sgomes** [comment]
Thanks, @Garbee!

**Pull request merged**
