### PR TITLE
fixing eslint related errors and warnings

### PR DESCRIPTION
**Pull request by andreasonny83**

### CODE REVIEW

**Comment by sgomes** [comment]
LGTM, thank you, @andreasonny83!

**Comment by Garbee** [comment]
This may cause a problem once `mdl-1.1` is merged up since it is re-doing some of the same fixes.

**Comment by andreasonny83** [comment]
I think that should only be a merge conflict to resolve in a really straightforward way

**Comment by sgomes** [comment]
Yup, small conflict, was easy to take care of. `mdl-1.1 has been merged into `master`.

**Pull request merged**
