### PR TITLE
Replace duplicated button demo (fixes #845)

### LINKED ISSUE #845: Very minor documentation mistake: Duplicate colored raised button example
I think this:
```html
<!-- Colored raised button -->
<button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">
  Button
</button>
<!-- Accent-colored raised button with ripple -->
<button class="mdl-button mdl-js-button mdl-button--raised mdl-button--accent mdl-js-ripple-effect">
  Button
</button>
<!-- Accent-colored raised button with ripple -->
<button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
  Button
</button>
```
should have `mdl-js-ripple-effect` removed from the second example and the comment changed to `<!-- Accent-colored raised button -->`.

### PR DESCRIPTION
**Pull request by surma**
r: @nicolasgarnier

### CODE REVIEW

**Comment by surma** [comment]
Hold on this.

**Comment by surma** [comment]
Waiting for @krazyeom

**Comment by surma** [comment]
I think @krazyeom [ACK'd this](https://github.com/google/material-design-lite/pull/851#issuecomment-119543001)]. @nicolasgarnier Your turn ;)

**Comment by nicolasgarnier** [comment]
LGTM!

**Pull request merged**
