### PR TITLE
Fix font weight

### PR DESCRIPTION
**Pull request by Garbee**
Per issue #649

### CODE REVIEW

**Comment by Garbee** [comment]
@addyosmani @santokii Says this is a major mis-alignment. Should be merged in an tagged up (1.0.1 I'd assume) ASAP.

**Comment by addyosmani** [comment]
Change LGTM. Thanks @Garbee! I'm probably going to hold off on a 1.0.1 till the morning just in case any other P0s come through. Is that reasonable @santokii or is this urgent enough that a re-tag is needed?

**Comment by santokii** [comment]
1.0.1 sgtm :) Thanks so much @Garbee !!!!

**Comment by Garbee** [comment]
Yea, we can probably wait. Also the same issue may have another major fix for cards upstream. I don't think holding off a few hours will hurt.

**Pull request closed without merging**
